// frontend/src/app/(auth)/setup/page.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { Upload, X, Loader2 } from 'lucide-react';
import * as authApi from '@/api/auth';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';

export default function SetupPage() {
  const router = useRouter();
  const [isCheckingSetup, setIsCheckingSetup] = useState(true);
  const [needsSetup, setNeedsSetup] = useState(false);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const usernameInputRef = useRef<HTMLInputElement>(null);
  const [showRestore, setShowRestore] = useState(false);
  const [restoreFile, setRestoreFile] = useState<File | null>(null);
  const [isRestoring, setIsRestoring] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Check if setup is needed on mount
  useEffect(() => {
    const checkSetup = async () => {
      try {
        const status = await authApi.checkSetupStatus();
        if (!status.needs_setup) {
          router.replace('/login');
          return;
        }
        setNeedsSetup(true);
      } catch {
        setError('Failed to check setup status');
      } finally {
        setIsCheckingSetup(false);
      }
    };
    checkSetup();
  }, [router]);

  // Focus username input when setup is confirmed needed
  useEffect(() => {
    if (needsSetup && usernameInputRef.current) {
      usernameInputRef.current.focus();
    }
  }, [needsSetup]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    // Validate username length
    if (username.length < 3) {
      setError('Username must be at least 3 characters');
      return;
    }

    // Validate password length
    if (password.length < 8) {
      setError('Password must be at least 8 characters');
      return;
    }

    // Validate passwords match
    if (password !== confirmPassword) {
      setError('Passwords do not match');
      return;
    }

    setIsSubmitting(true);

    try {
      await authApi.createInitialAdmin(username, password);
      router.push('/login');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create admin account');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleRestore = async () => {
    if (!restoreFile) return;

    setError(null);
    setIsRestoring(true);

    try {
      await authApi.setupRestore(restoreFile);
      router.push('/login');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to restore from backup');
    } finally {
      setIsRestoring(false);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (!file.name.endsWith('.tar.gz')) {
        setError('Please select a .tar.gz backup file');
        return;
      }
      setRestoreFile(file);
      setError(null);
    }
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  const cancelRestore = () => {
    setShowRestore(false);
    setRestoreFile(null);
    setError(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  // Show loading state while checking setup status
  if (isCheckingSetup) {
    return (
      <Card className="w-full max-w-sm">
        <CardContent className="flex items-center justify-center p-6">
          <div className="text-muted-foreground">Checking setup status...</div>
        </CardContent>
      </Card>
    );
  }

  // Don't render the form if setup is not needed (redirect is happening)
  if (!needsSetup) {
    return null;
  }

  return (
    <Card className="w-full max-w-sm">
      <CardHeader className="space-y-1 text-center">
        <CardTitle className="text-2xl font-bold">
          {showRestore ? 'Restore from Backup' : 'Create Admin Account'}
        </CardTitle>
        <CardDescription>
          {showRestore
            ? 'Upload a backup file to restore your data'
            : 'Set up your administrator account to get started'}
        </CardDescription>
      </CardHeader>
      <CardContent>
        {error && (
          <Alert variant="destructive" className="mb-4">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {!showRestore ? (
          <>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="username">Username</Label>
                <Input
                  ref={usernameInputRef}
                  id="username"
                  type="text"
                  placeholder="Choose a username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                  minLength={3}
                  autoComplete="username"
                  disabled={isSubmitting}
                />
                <p className="text-sm text-muted-foreground">
                  Must be at least 3 characters
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="Enter a secure password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  minLength={8}
                  autoComplete="new-password"
                  disabled={isSubmitting}
                />
                <p className="text-sm text-muted-foreground">
                  Must be at least 8 characters
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="confirmPassword">Confirm Password</Label>
                <Input
                  id="confirmPassword"
                  type="password"
                  placeholder="Confirm your password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  required
                  autoComplete="new-password"
                  disabled={isSubmitting}
                />
              </div>

              <Button
                type="submit"
                className="w-full"
                disabled={isSubmitting || !username || !password || !confirmPassword}
              >
                {isSubmitting ? 'Creating Account...' : 'Create Admin Account'}
              </Button>

              <p className="text-center text-sm text-muted-foreground">
                This account will have full administrative privileges
              </p>
            </form>

            <div className="mt-4 text-center">
              <button
                type="button"
                onClick={() => setShowRestore(true)}
                className="text-sm text-muted-foreground hover:text-foreground hover:underline"
              >
                Restore from backup
              </button>
            </div>
          </>
        ) : (
          <div className="space-y-4">
            <input
              ref={fileInputRef}
              type="file"
              accept=".tar.gz"
              onChange={handleFileSelect}
              className="hidden"
            />

            {!restoreFile ? (
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="w-full rounded-lg border-2 border-dashed border-muted-foreground/25 p-8 text-center hover:border-muted-foreground/50 transition-colors"
                disabled={isRestoring}
              >
                <Upload className="mx-auto h-8 w-8 text-muted-foreground mb-2" />
                <p className="text-sm text-muted-foreground">
                  Click to select a backup file
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  .tar.gz files only
                </p>
              </button>
            ) : (
              <div className="rounded-lg border p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3 min-w-0">
                    <Upload className="h-5 w-5 text-muted-foreground flex-shrink-0" />
                    <div className="min-w-0">
                      <p className="text-sm font-medium truncate">{restoreFile.name}</p>
                      <p className="text-xs text-muted-foreground">
                        {formatFileSize(restoreFile.size)}
                      </p>
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => {
                      setRestoreFile(null);
                      if (fileInputRef.current) fileInputRef.current.value = '';
                    }}
                    className="text-muted-foreground hover:text-foreground"
                    disabled={isRestoring}
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
              </div>
            )}

            <Button
              onClick={handleRestore}
              className="w-full"
              disabled={!restoreFile || isRestoring}
            >
              {isRestoring ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Restoring...
                </>
              ) : (
                'Restore'
              )}
            </Button>

            <button
              type="button"
              onClick={cancelRestore}
              className="w-full text-sm text-muted-foreground hover:text-foreground hover:underline"
              disabled={isRestoring}
            >
              Cancel
            </button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// frontend/src/routes/setup/+page.svelte
<script lang="ts">
  import { auth } from '$lib/stores';
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';

  let username = '';
  let password = '';
  let confirmPassword = '';
  let isLoading = false;
  let error = '';
  let needsSetup: boolean | null = null; // null means we're still checking
  let usernameInput: HTMLInputElement;

  onMount(async () => {
    // Check if setup is actually needed
    const status = await auth.checkSetupStatus();
    if (!status.needs_setup) {
      // If setup is not needed, redirect to login
      goto('/login');
    } else {
      needsSetup = true;
      // Focus the username input after setup status is confirmed
      if (usernameInput) {
        usernameInput.focus();
      }
    }
  });

  function validateForm(): boolean {
    if (!username || !password || !confirmPassword) {
      error = 'Please fill in all fields';
      return false;
    }

    if (username.length < 3) {
      error = 'Username must be at least 3 characters long';
      return false;
    }

    if (password.length < 8) {
      error = 'Password must be at least 8 characters long';
      return false;
    }

    if (password !== confirmPassword) {
      error = 'Passwords do not match';
      return false;
    }

    return true;
  }

  async function handleSetup() {
    if (!validateForm()) {
      return;
    }

    isLoading = true;
    error = '';

    try {
      await auth.createInitialAdmin(username, password);
      // Redirect to login page after successful setup
      goto('/login');
    } catch (err) {
      error = err instanceof Error ? err.message : 'Setup failed';
    } finally {
      isLoading = false;
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      handleSetup();
    }
  }
</script>

<svelte:head>
  <title>Initial Setup - Nexorious</title>
</svelte:head>

{#if needsSetup === true}
<div class="flex min-h-screen flex-col justify-center bg-gray-50 py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white px-4 py-8 shadow sm:rounded-lg sm:px-10">
      <!-- Header -->
      <div class="sm:mx-auto sm:w-full sm:max-w-md mb-8">
        <h1 class="text-center text-3xl font-bold tracking-tight text-gray-900">
          Welcome to Nexorious
        </h1>
        <p class="mt-2 text-center text-sm text-gray-600">
          Let's set up your admin account to get started
        </p>
      </div>

      {#if error}
        <div class="mb-4 rounded-md bg-red-50 p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-3">
              <p class="text-sm text-red-800">
                {error}
              </p>
            </div>
          </div>
        </div>
      {/if}

      <form onsubmit={(e) => { e.preventDefault(); handleSetup(); }} class="space-y-6">
        <div>
          <label for="username" class="form-label">
            Admin Username
          </label>
          <input
            id="username"
            type="text"
            bind:value={username}
            bind:this={usernameInput}
            onkeydown={handleKeydown}
            required
            minlength="3"
            placeholder="Choose a username"
            class="form-input"
            disabled={isLoading}
          />
          <p class="mt-1 text-sm text-gray-500">
            This will be your administrator username
          </p>
        </div>

        <div>
          <label for="password" class="form-label">
            Password
          </label>
          <input
            id="password"
            type="password"
            bind:value={password}
            onkeydown={handleKeydown}
            required
            minlength="8"
            placeholder="Enter a secure password"
            class="form-input"
            disabled={isLoading}
          />
          <p class="mt-1 text-sm text-gray-500">
            Must be at least 8 characters long
          </p>
        </div>

        <div>
          <label for="confirmPassword" class="form-label">
            Confirm Password
          </label>
          <input
            id="confirmPassword"
            type="password"
            bind:value={confirmPassword}
            onkeydown={handleKeydown}
            required
            placeholder="Confirm your password"
            class="form-input"
            disabled={isLoading}
          />
        </div>

        <div class="pt-4">
          <button
            type="submit"
            disabled={isLoading}
            class="flex w-full justify-center rounded-md bg-primary-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {#if isLoading}
              <svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Creating Admin Account...
            {:else}
              Create Admin Account
            {/if}
          </button>
        </div>

        <div class="mt-4 text-center">
          <p class="text-sm text-gray-500">
            This account will have full administrative privileges
          </p>
        </div>
      </form>
    </div>
  </div>
</div>
{:else}
  <!-- Show loading state while checking setup status -->
  <div class="flex min-h-screen items-center justify-center">
    <div class="text-center">
      <svg class="animate-spin h-8 w-8 text-primary-500 mx-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
      <p class="mt-2 text-gray-600">Checking setup status...</p>
    </div>
  </div>
{/if}
