// frontend/src/lib/components/ProgressStatistics.svelte
<script lang="ts">
  import { ProgressBar } from '$lib/components';
  import type { UserGame } from '$lib/stores/user-games.svelte';

  interface Props {
    userGames: UserGame[];
    class?: string;
  }

  let { userGames, class: className = '' }: Props = $props();

  // Calculate statistics
  const totalGames = $derived(userGames.length);
  const statusCounts = $derived({
    not_started: userGames.filter(g => g.play_status === 'not_started').length,
    in_progress: userGames.filter(g => g.play_status === 'in_progress').length,
    completed: userGames.filter(g => g.play_status === 'completed').length,
    mastered: userGames.filter(g => g.play_status === 'mastered').length,
    dominated: userGames.filter(g => g.play_status === 'dominated').length,
    shelved: userGames.filter(g => g.play_status === 'shelved').length,
    dropped: userGames.filter(g => g.play_status === 'dropped').length,
    replay: userGames.filter(g => g.play_status === 'replay').length
  });

  // Calculate completion metrics
  const completedTotal = $derived(statusCounts.completed + statusCounts.mastered + statusCounts.dominated);
  const completionRate = $derived(totalGames > 0 ? (completedTotal / totalGames) * 100 : 0);
  const activeGames = $derived(statusCounts.in_progress + statusCounts.replay);
  const abandonedGames = $derived(statusCounts.dropped + statusCounts.shelved);

  // Calculate time metrics
  const totalHoursPlayed = $derived(userGames.reduce((sum, g) => sum + (g.hours_played || 0), 0));
  const averageHoursPerGame = $derived(totalGames > 0 ? totalHoursPlayed / totalGames : 0);
  const completedGamesWithHours = $derived(userGames.filter(g => 
    (g.play_status === 'completed' || g.play_status === 'mastered' || g.play_status === 'dominated') && 
    g.hours_played > 0
  ));
  const averageCompletionTime = $derived(completedGamesWithHours.length > 0 
    ? completedGamesWithHours.reduce((sum, g) => sum + g.hours_played, 0) / completedGamesWithHours.length 
    : 0);

  // Status configuration
  const statusConfig = [
    { 
      key: 'not_started', 
      label: 'Not Started', 
      color: 'gray' as const,
      icon: '⏸️',
      description: 'Games waiting to be played'
    },
    { 
      key: 'in_progress', 
      label: 'In Progress', 
      color: 'blue' as const,
      icon: '🎮',
      description: 'Currently playing'
    },
    { 
      key: 'completed', 
      label: 'Completed', 
      color: 'green' as const,
      icon: '✅',
      description: 'Main story finished'
    },
    { 
      key: 'mastered', 
      label: 'Mastered', 
      color: 'purple' as const,
      icon: '🏆',
      description: 'All major content done'
    },
    { 
      key: 'dominated', 
      label: 'Dominated', 
      color: 'yellow' as const,
      icon: '👑',
      description: '100% completion'
    },
    { 
      key: 'shelved', 
      label: 'Shelved', 
      color: 'orange' as const,
      icon: '📚',
      description: 'On hold for later'
    },
    { 
      key: 'dropped', 
      label: 'Dropped', 
      color: 'red' as const,
      icon: '❌',
      description: 'No longer playing'
    },
    { 
      key: 'replay', 
      label: 'Replay', 
      color: 'blue' as const,
      icon: '🔄',
      description: 'Playing again'
    }
  ];
</script>

<div class="space-y-6 {className}">
  <!-- Overview Stats -->
  <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
    <div class="bg-white rounded-lg border border-gray-200 p-4">
      <div class="text-sm font-medium text-gray-500">Total Games</div>
      <div class="mt-1 text-2xl font-bold text-gray-900">{totalGames}</div>
    </div>
    <div class="bg-white rounded-lg border border-gray-200 p-4">
      <div class="text-sm font-medium text-gray-500">Completion Rate</div>
      <div class="mt-1 text-2xl font-bold text-green-600">{completionRate.toFixed(1)}%</div>
    </div>
    <div class="bg-white rounded-lg border border-gray-200 p-4">
      <div class="text-sm font-medium text-gray-500">Total Hours</div>
      <div class="mt-1 text-2xl font-bold text-blue-600">{totalHoursPlayed.toLocaleString()}</div>
    </div>
    <div class="bg-white rounded-lg border border-gray-200 p-4">
      <div class="text-sm font-medium text-gray-500">Active Games</div>
      <div class="mt-1 text-2xl font-bold text-purple-600">{activeGames}</div>
    </div>
  </div>

  <!-- Detailed Progress Breakdown -->
  <div class="bg-white rounded-lg border border-gray-200 p-6">
    <h3 class="text-lg font-semibold text-gray-900 mb-4">Progress Breakdown</h3>
    <div class="space-y-4">
      {#each statusConfig as status}
        {@const count = statusCounts[status.key as keyof typeof statusCounts]}
        {@const percentage = totalGames > 0 ? (count / totalGames) * 100 : 0}
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <div class="flex items-center space-x-2">
              <span class="text-lg">{status.icon}</span>
              <div>
                <span class="font-medium text-gray-900">{status.label}</span>
                <span class="text-sm text-gray-500 ml-2">({count} {count === 1 ? 'game' : 'games'})</span>
              </div>
            </div>
            <span class="text-sm text-gray-600">{percentage.toFixed(1)}%</span>
          </div>
          <ProgressBar
            value={percentage}
            max={100}
            color={status.color}
            size="sm"
            showPercentage={false}
          />
          <p class="text-xs text-gray-500">{status.description}</p>
        </div>
      {/each}
    </div>
  </div>

  <!-- Completion Journey -->
  <div class="bg-white rounded-lg border border-gray-200 p-6">
    <h3 class="text-lg font-semibold text-gray-900 mb-4">Completion Journey</h3>
    <div class="relative">
      <div class="absolute left-8 top-8 bottom-0 w-0.5 bg-gray-200"></div>
      <div class="space-y-6">
        <div class="flex items-center space-x-4">
          <div class="relative z-10 w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center text-2xl">
            ⏸️
          </div>
          <div class="flex-1">
            <h4 class="font-medium text-gray-900">Not Started</h4>
            <p class="text-sm text-gray-600">{statusCounts.not_started} games waiting</p>
          </div>
        </div>
        
        <div class="flex items-center space-x-4">
          <div class="relative z-10 w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center text-2xl">
            🎮
          </div>
          <div class="flex-1">
            <h4 class="font-medium text-gray-900">In Progress</h4>
            <p class="text-sm text-gray-600">{statusCounts.in_progress} games active</p>
          </div>
        </div>
        
        <div class="flex items-center space-x-4">
          <div class="relative z-10 w-16 h-16 bg-green-100 rounded-full flex items-center justify-center text-2xl">
            ✅
          </div>
          <div class="flex-1">
            <h4 class="font-medium text-gray-900">Completed</h4>
            <p class="text-sm text-gray-600">{statusCounts.completed} main stories finished</p>
          </div>
        </div>
        
        <div class="flex items-center space-x-4">
          <div class="relative z-10 w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center text-2xl">
            🏆
          </div>
          <div class="flex-1">
            <h4 class="font-medium text-gray-900">Mastered</h4>
            <p class="text-sm text-gray-600">{statusCounts.mastered} games fully explored</p>
          </div>
        </div>
        
        <div class="flex items-center space-x-4">
          <div class="relative z-10 w-16 h-16 bg-yellow-100 rounded-full flex items-center justify-center text-2xl">
            👑
          </div>
          <div class="flex-1">
            <h4 class="font-medium text-gray-900">Dominated</h4>
            <p class="text-sm text-gray-600">{statusCounts.dominated} games at 100%</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Time Investment -->
  {#if totalHoursPlayed > 0}
    <div class="bg-white rounded-lg border border-gray-200 p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Time Investment</h3>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div class="text-center">
          <div class="text-3xl font-bold text-blue-600">{totalHoursPlayed.toLocaleString()}</div>
          <div class="text-sm text-gray-500 mt-1">Total Hours Played</div>
        </div>
        <div class="text-center">
          <div class="text-3xl font-bold text-green-600">{averageHoursPerGame.toFixed(1)}</div>
          <div class="text-sm text-gray-500 mt-1">Average Hours per Game</div>
        </div>
        <div class="text-center">
          <div class="text-3xl font-bold text-purple-600">{averageCompletionTime.toFixed(1)}</div>
          <div class="text-sm text-gray-500 mt-1">Average Completion Time</div>
        </div>
      </div>
    </div>
  {/if}
</div>

// frontend/src/components/dashboard/progress-statistics.tsx

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PlayStatus } from '@/types';
import { StatusProgress } from './status-progress';
import { statusIcons, statusLabels } from './status-progress-data';

interface CollectionStats {
  totalGames: number;
  completionStats: Record<PlayStatus, number>;
  ownershipStats: Record<string, number>;
  platformStats: Record<string, number>;
  genreStats: Record<string, number>;
  pileOfShame: number;
  completionRate: number;
  averageRating: number | null;
  totalHoursPlayed: number;
}

interface ProgressStatisticsProps {
  stats: CollectionStats;
  className?: string;
}

// Order of play statuses in the progress journey
const statusOrder: PlayStatus[] = [
  PlayStatus.NOT_STARTED,
  PlayStatus.IN_PROGRESS,
  PlayStatus.COMPLETED,
  PlayStatus.MASTERED,
  PlayStatus.DOMINATED,
  PlayStatus.SHELVED,
  PlayStatus.DROPPED,
  PlayStatus.REPLAY,
];

// Background colors for journey icons
const statusBgColors: Record<PlayStatus, string> = {
  [PlayStatus.NOT_STARTED]: 'bg-gray-100',
  [PlayStatus.IN_PROGRESS]: 'bg-blue-100',
  [PlayStatus.COMPLETED]: 'bg-green-100',
  [PlayStatus.MASTERED]: 'bg-purple-100',
  [PlayStatus.DOMINATED]: 'bg-yellow-100',
  [PlayStatus.SHELVED]: 'bg-orange-100',
  [PlayStatus.DROPPED]: 'bg-red-100',
  [PlayStatus.REPLAY]: 'bg-cyan-100',
};

// Journey statuses (main progression)
const journeyStatuses: PlayStatus[] = [
  PlayStatus.NOT_STARTED,
  PlayStatus.IN_PROGRESS,
  PlayStatus.COMPLETED,
  PlayStatus.MASTERED,
  PlayStatus.DOMINATED,
];

const journeyDescriptions: Record<PlayStatus, string> = {
  [PlayStatus.NOT_STARTED]: 'games waiting',
  [PlayStatus.IN_PROGRESS]: 'games active',
  [PlayStatus.COMPLETED]: 'main stories finished',
  [PlayStatus.MASTERED]: 'games fully explored',
  [PlayStatus.DOMINATED]: 'games at 100%',
  [PlayStatus.SHELVED]: 'games on hold',
  [PlayStatus.DROPPED]: 'games stopped',
  [PlayStatus.REPLAY]: 'games replaying',
};

export function ProgressStatistics({
  stats,
  className,
}: ProgressStatisticsProps) {
  const {
    totalGames,
    completionStats,
    completionRate,
    totalHoursPlayed,
  } = stats;

  // Calculate active games (in progress + replay)
  const activeGames =
    (completionStats[PlayStatus.IN_PROGRESS] || 0) +
    (completionStats[PlayStatus.REPLAY] || 0);

  // Calculate time metrics
  const averageHoursPerGame = totalGames > 0 ? totalHoursPlayed / totalGames : 0;

  // Calculate completed games with hours for average completion time
  const completedCount =
    (completionStats[PlayStatus.COMPLETED] || 0) +
    (completionStats[PlayStatus.MASTERED] || 0) +
    (completionStats[PlayStatus.DOMINATED] || 0);

  // Estimate average completion time (rough approximation)
  const averageCompletionTime =
    completedCount > 0 && totalHoursPlayed > 0
      ? totalHoursPlayed / completedCount
      : 0;

  return (
    <div className={className}>
      {/* Overview Stats */}
      <div className="mb-6 grid grid-cols-2 gap-4 md:grid-cols-4">
        <Card>
          <CardContent className="p-4">
            <div className="text-sm font-medium text-muted-foreground">
              Total Games
            </div>
            <div className="mt-1 text-2xl font-bold">{totalGames}</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-sm font-medium text-muted-foreground">
              Completion Rate
            </div>
            <div className="mt-1 text-2xl font-bold text-green-600">
              {completionRate.toFixed(1)}%
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-sm font-medium text-muted-foreground">
              Total Hours
            </div>
            <div className="mt-1 text-2xl font-bold text-blue-600">
              {totalHoursPlayed.toLocaleString()}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-sm font-medium text-muted-foreground">
              Active Games
            </div>
            <div className="mt-1 text-2xl font-bold text-purple-600">
              {activeGames}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Progress Breakdown */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Progress Breakdown</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {statusOrder.map((status) => (
            <StatusProgress
              key={status}
              status={status}
              count={completionStats[status] || 0}
              total={totalGames}
              showDescription
            />
          ))}
        </CardContent>
      </Card>

      {/* Completion Journey */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Completion Journey</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="relative">
            <div className="absolute bottom-0 left-8 top-8 w-0.5 bg-border"></div>
            <div className="space-y-6">
              {journeyStatuses.map((status) => (
                <div key={status} className="flex items-center gap-4">
                  <div
                    className={`relative z-10 flex h-16 w-16 items-center justify-center rounded-full text-2xl ${statusBgColors[status]}`}
                    role="img"
                    aria-label={statusLabels[status]}
                  >
                    {statusIcons[status]}
                  </div>
                  <div className="flex-1">
                    <h4 className="font-medium">{statusLabels[status]}</h4>
                    <p className="text-sm text-muted-foreground">
                      {completionStats[status] || 0} {journeyDescriptions[status]}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Time Investment */}
      {totalHoursPlayed > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Time Investment</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
              <div className="text-center">
                <div className="text-3xl font-bold text-blue-600">
                  {totalHoursPlayed.toLocaleString()}
                </div>
                <div className="mt-1 text-sm text-muted-foreground">
                  Total Hours Played
                </div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-green-600">
                  {averageHoursPerGame.toFixed(1)}
                </div>
                <div className="mt-1 text-sm text-muted-foreground">
                  Average Hours per Game
                </div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-purple-600">
                  {averageCompletionTime.toFixed(1)}
                </div>
                <div className="mt-1 text-sm text-muted-foreground">
                  Average Completion Time
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
