// frontend/src/routes/admin/users/[id]/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { admin, auth } from '$lib/stores';
  import { RouteGuard } from '$lib/components';
  import type { AdminUser, UserDeletionImpact } from '$lib/stores/admin.svelte';

  // Get user ID from route params
  const userId = $derived($page.params.id);

  let user = $state<AdminUser | null>(null);
  let isLoading = $state(true);
  let isSaving = $state(false);
  let error = $state<string | null>(null);
  let successMessage = $state<string | null>(null);
  let showDeleteDialog = $state(false);
  let deletionStep = $state(1); // 1: impact preview, 2: confirmation
  let deletionImpact = $state<UserDeletionImpact | null>(null);
  let isDeletionImpactLoading = $state(false);
  let usernameConfirmation = $state('');
  let showPasswordResetConfirmation = $state(false);
  let newPassword = $state('');

  // Form state
  let formData = $state({
    username: '',
    isActive: true,
    isAdmin: false
  });
  let originalData = $state({
    username: '',
    isActive: true,
    isAdmin: false
  });

  // Reactive statement to check if current user is editing themselves
  const isEditingSelf = $derived(userId ? auth.value.user?.id === userId : false);
  const hasChanges = $derived(
    formData.username !== originalData.username ||
    formData.isActive !== originalData.isActive ||
    formData.isAdmin !== originalData.isAdmin
  );

  onMount(async () => {
    // Check if user is admin
    if (!auth.value.user?.isAdmin) {
      goto('/dashboard');
      return;
    }

    await loadUser();
  });

  async function loadUser() {
    // Check if userId exists
    if (!userId) {
      error = 'User ID is required';
      isLoading = false;
      return;
    }

    try {
      isLoading = true;
      error = null;
      user = await admin.getUserById(userId);
      
      // Initialize form data
      formData = {
        username: user.username,
        isActive: user.isActive,
        isAdmin: user.isAdmin
      };
      originalData = { ...formData };
    } catch (err) {
      console.error('Failed to load user:', err);
      error = err instanceof Error ? err.message : 'Failed to load user';
    } finally {
      isLoading = false;
    }
  }

  async function handleSave() {
    if (!user || !hasChanges) return;

    try {
      isSaving = true;
      error = null;
      successMessage = null;

      // Validate form
      if (!formData.username.trim()) {
        throw new Error('Username is required');
      }

      // Check for self-modification restrictions
      if (isEditingSelf) {
        if (!formData.isActive) {
          throw new Error('You cannot deactivate your own account');
        }
        if (!formData.isAdmin) {
          throw new Error('You cannot remove your own admin privileges');
        }
      }

      const updatedUser = await admin.updateUser(user.id, {
        username: formData.username.trim(),
        isActive: formData.isActive,
        isAdmin: formData.isAdmin
      });

      // Update local state
      user = updatedUser;
      originalData = { ...formData };
      successMessage = 'User updated successfully';
      
      // Clear success message after 3 seconds
      setTimeout(() => {
        successMessage = null;
      }, 3000);
    } catch (err) {
      console.error('Failed to update user:', err);
      error = err instanceof Error ? err.message : 'Failed to update user';
    } finally {
      isSaving = false;
    }
  }

  async function handlePasswordReset() {
    if (!user || !newPassword.trim()) return;

    try {
      isSaving = true;
      error = null;
      successMessage = null;

      await admin.resetUserPassword(user.id, newPassword.trim());
      
      successMessage = 'Password reset successfully. User will need to log in again.';
      newPassword = '';
      showPasswordResetConfirmation = false;
      
      // Clear success message after 5 seconds
      setTimeout(() => {
        successMessage = null;
      }, 5000);
    } catch (err) {
      console.error('Failed to reset password:', err);
      error = err instanceof Error ? err.message : 'Failed to reset password';
    } finally {
      isSaving = false;
    }
  }

  async function startDeletion() {
    if (!user) return;

    showDeleteDialog = true;
    deletionStep = 1;
    usernameConfirmation = '';
    
    try {
      isDeletionImpactLoading = true;
      deletionImpact = await admin.getUserDeletionImpact(user.id);
    } catch (err) {
      console.error('Failed to get deletion impact:', err);
      error = err instanceof Error ? err.message : 'Failed to get deletion impact';
      showDeleteDialog = false;
    } finally {
      isDeletionImpactLoading = false;
    }
  }

  function goToConfirmation() {
    deletionStep = 2;
  }

  function cancelDeletion() {
    showDeleteDialog = false;
    deletionStep = 1;
    deletionImpact = null;
    usernameConfirmation = '';
    error = null;
  }

  async function confirmDeletion() {
    if (!user || !deletionImpact || usernameConfirmation !== user.username) return;

    try {
      isSaving = true;
      error = null;

      await admin.deleteUser(user.id);
      
      // Redirect to users list after successful deletion
      goto('/admin/users');
    } catch (err) {
      console.error('Failed to delete user:', err);
      error = err instanceof Error ? err.message : 'Failed to delete user';
      isSaving = false;
    }
  }

  function resetForm() {
    formData = { ...originalData };
    error = null;
    successMessage = null;
  }

  function formatDate(dateString: string) {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  function getUserStatusBadge(user: AdminUser) {
    const badges = [];
    
    if (user.isAdmin) {
      badges.push({ text: 'Admin', class: 'bg-purple-100 text-purple-800' });
    }
    
    if (!user.isActive) {
      badges.push({ text: 'Inactive', class: 'bg-red-100 text-red-800' });
    } else if (!user.isAdmin) {
      badges.push({ text: 'User', class: 'bg-green-100 text-green-800' });
    }
    
    return badges;
  }
</script>

<RouteGuard requireAdmin={true}>
  <div class="space-y-6">
    <!-- Header -->
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="sm:flex-auto">
        <div class="flex items-center space-x-4">
          <a
            href="/admin/users"
            class="text-gray-400 hover:text-gray-600"
            title="Back to users"
          >
            ←
          </a>
          <div>
            <h1 class="text-3xl font-bold leading-tight text-gray-900">
              {#if isLoading}
                Loading User...
              {:else if user}
                Edit User: {user.username}
              {:else}
                User Not Found
              {/if}
            </h1>
            {#if user && !isLoading}
              <p class="mt-2 text-sm text-gray-700">
                User ID: {user.id} • Created {formatDate(user.createdAt)}
                {#if isEditingSelf}
                  <span class="ml-2 text-primary-600 font-medium">(This is you)</span>
                {/if}
              </p>
            {/if}
          </div>
        </div>
      </div>
    </div>

    {#if error}
      <div class="rounded-md bg-red-50 p-4">
        <div class="flex">
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800">Error</h3>
            <div class="mt-2 text-sm text-red-700">
              <p>{error}</p>
            </div>
            <div class="mt-4">
              <button
                onclick={() => { error = null; }}
                type="button"
                class="rounded-md bg-red-50 px-3 py-2 text-sm font-medium text-red-800 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2"
              >
                Dismiss
              </button>
            </div>
          </div>
        </div>
      </div>
    {/if}

    {#if successMessage}
      <div class="rounded-md bg-green-50 p-4">
        <div class="flex">
          <div class="ml-3">
            <h3 class="text-sm font-medium text-green-800">Success</h3>
            <div class="mt-2 text-sm text-green-700">
              <p>{successMessage}</p>
            </div>
          </div>
        </div>
      </div>
    {/if}

    {#if isLoading}
      <div class="flex justify-center py-12">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600" role="status" aria-label="Loading"></div>
      </div>
    {:else if user}
      <!-- User Edit Form -->
      <div class="bg-white shadow rounded-lg">
        <div class="px-4 py-5 sm:p-6">
          <h3 class="text-lg leading-6 font-medium text-gray-900 mb-6">User Information</h3>
          
          <!-- Current Status Display -->
          <div class="mb-6 p-4 bg-gray-50 rounded-lg">
            <div class="flex items-center space-x-4">
              <div class="h-12 w-12 rounded-full bg-gray-200 flex items-center justify-center">
                <span class="text-lg font-medium text-gray-700">
                  {user.username.charAt(0).toUpperCase()}
                </span>
              </div>
              <div>
                <p class="text-lg font-medium text-gray-900">{user.username}</p>
                <div class="flex flex-wrap gap-2 mt-1">
                  {#each getUserStatusBadge(user) as badge}
                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium {badge.class}">
                      {badge.text}
                    </span>
                  {/each}
                </div>
                <p class="text-sm text-gray-500 mt-1">Last updated {formatDate(user.updatedAt)}</p>
              </div>
            </div>
          </div>

          <form onsubmit={(e) => { e.preventDefault(); handleSave(); }} class="space-y-6">
            <!-- Username -->
            <div>
              <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
              <div class="mt-2">
                <input
                  type="text"
                  name="username"
                  id="username"
                  bind:value={formData.username}
                  required
                  class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>

            <!-- Account Status -->
            <div class="space-y-4">
              <h4 class="text-sm font-medium text-gray-900">Account Status</h4>
              
              <!-- Active Status -->
              <div class="flex items-center space-x-3">
                <input
                  type="checkbox"
                  id="isActive"
                  bind:checked={formData.isActive}
                  disabled={isEditingSelf}
                  class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded disabled:opacity-50"
                />
                <label for="isActive" class="text-sm text-gray-700">
                  Account is active
                  {#if isEditingSelf}
                    <span class="text-gray-400">(Cannot modify your own account status)</span>
                  {/if}
                </label>
              </div>

              <!-- Admin Status -->
              <div class="flex items-center space-x-3">
                <input
                  type="checkbox"
                  id="isAdmin"
                  bind:checked={formData.isAdmin}
                  disabled={isEditingSelf}
                  class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded disabled:opacity-50"
                />
                <label for="isAdmin" class="text-sm text-gray-700">
                  Administrator privileges
                  {#if isEditingSelf}
                    <span class="text-gray-400">(Cannot modify your own admin privileges)</span>
                  {/if}
                </label>
              </div>
            </div>

            <!-- Form Actions -->
            <div class="flex justify-between pt-4">
              <div class="flex space-x-3">
                <button
                  type="submit"
                  disabled={!hasChanges || isSaving}
                  class="inline-flex justify-center rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {#if isSaving}
                    Saving...
                  {:else}
                    Save Changes
                  {/if}
                </button>
                <button
                  type="button"
                  onclick={resetForm}
                  disabled={!hasChanges || isSaving}
                  class="inline-flex justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Reset
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>

      <!-- Dangerous Actions -->
      <div class="bg-white shadow rounded-lg">
        <div class="px-4 py-5 sm:p-6">
          <h3 class="text-lg leading-6 font-medium text-gray-900 mb-6">Account Actions</h3>
          
          <div class="space-y-4">
            <!-- Password Reset -->
            <div class="border rounded-lg p-4">
              <h4 class="text-sm font-medium text-gray-900 mb-2">Reset Password</h4>
              <p class="text-sm text-gray-600 mb-4">
                Generate a new password for this user. They will need to log in again with the new password.
              </p>
              
              {#if showPasswordResetConfirmation}
                <div class="space-y-3">
                  <div>
                    <label for="newPassword" class="block text-sm font-medium leading-6 text-gray-900">New Password</label>
                    <input
                      type="password"
                      id="newPassword"
                      bind:value={newPassword}
                      placeholder="Enter new password"
                      class="mt-1 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
                    />
                  </div>
                  <div class="flex space-x-3">
                    <button
                      onclick={handlePasswordReset}
                      disabled={!newPassword.trim() || isSaving}
                      class="inline-flex justify-center rounded-md bg-yellow-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-yellow-600 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {#if isSaving}
                        Resetting...
                      {:else}
                        Reset Password
                      {/if}
                    </button>
                    <button
                      onclick={() => { showPasswordResetConfirmation = false; newPassword = ''; }}
                      disabled={isSaving}
                      class="inline-flex justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 disabled:opacity-50"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              {:else}
                <button
                  onclick={() => { showPasswordResetConfirmation = true; }}
                  disabled={isSaving}
                  class="inline-flex justify-center rounded-md bg-yellow-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-yellow-600 disabled:opacity-50"
                >
                  Reset Password
                </button>
              {/if}
            </div>

            <!-- Delete User -->
            {#if !isEditingSelf}
              <div class="border border-red-200 rounded-lg p-4">
                <h4 class="text-sm font-medium text-red-900 mb-2">Delete User</h4>
                <p class="text-sm text-red-600 mb-4">
                  Permanently delete this user account and all associated data. This action cannot be undone.
                </p>
                
                <button
                  onclick={startDeletion}
                  disabled={isSaving}
                  class="inline-flex justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600 disabled:opacity-50"
                >
                  Delete User
                </button>
              </div>
            {/if}
          </div>
        </div>
      </div>
    {:else}
      <!-- User Not Found -->
      <div class="bg-white shadow rounded-lg">
        <div class="px-4 py-5 sm:p-6">
          <div class="text-center py-12">
            <h3 class="text-lg font-medium text-gray-900 mb-2">User Not Found</h3>
            <p class="text-gray-500 mb-4">
              The user with ID "{userId || 'unknown'}" could not be found.
            </p>
            <a
              href="/admin/users"
              class="inline-flex items-center justify-center rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600"
            >
              Back to Users
            </a>
          </div>
        </div>
      </div>
    {/if}
  </div>

  <!-- Delete User Dialog -->
  {#if showDeleteDialog}
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity z-50" aria-labelledby="modal-title" role="dialog" aria-modal="true">
      <div class="fixed inset-0 overflow-y-auto">
        <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
          <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
            
            {#if deletionStep === 1}
              <!-- Step 1: Data Impact Preview -->
              <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
                <div class="sm:flex sm:items-start">
                  <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                    <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                    </svg>
                  </div>
                  <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left w-full">
                    <h3 class="text-lg font-semibold leading-6 text-gray-900" id="modal-title">
                      Delete User: {user?.username}
                    </h3>
                    
                    {#if isDeletionImpactLoading}
                      <div class="mt-4 flex justify-center">
                        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-red-600"></div>
                      </div>
                    {:else if deletionImpact}
                      <div class="mt-4">
                        <p class="text-sm text-gray-500 mb-4">
                          This action will permanently delete the following data:
                        </p>
                        
                        <div class="bg-red-50 border border-red-200 rounded-lg p-4 space-y-2">
                          <div class="flex justify-between">
                            <span class="text-sm text-gray-700">Games in collection:</span>
                            <span class="text-sm font-medium text-red-900">{deletionImpact.total_games}</span>
                          </div>
                          <div class="flex justify-between">
                            <span class="text-sm text-gray-700">User-created tags:</span>
                            <span class="text-sm font-medium text-red-900">{deletionImpact.total_tags}</span>
                          </div>
                          <div class="flex justify-between">
                            <span class="text-sm text-gray-700">Wishlist items:</span>
                            <span class="text-sm font-medium text-red-900">{deletionImpact.total_wishlist_items}</span>
                          </div>
                          <div class="flex justify-between">
                            <span class="text-sm text-gray-700">Import jobs:</span>
                            <span class="text-sm font-medium text-red-900">{deletionImpact.total_import_jobs}</span>
                          </div>
                          <div class="flex justify-between">
                            <span class="text-sm text-gray-700">Active sessions:</span>
                            <span class="text-sm font-medium text-red-900">{deletionImpact.total_sessions}</span>
                          </div>
                        </div>
                        
                        <div class="mt-4 p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
                          <p class="text-sm text-yellow-800">
                            <strong>Warning:</strong> {deletionImpact.warning}
                          </p>
                        </div>
                      </div>
                    {/if}
                  </div>
                </div>
              </div>
              <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                <button
                  type="button"
                  onclick={goToConfirmation}
                  disabled={isDeletionImpactLoading || !deletionImpact}
                  class="inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto disabled:opacity-50"
                >
                  Continue
                </button>
                <button
                  type="button"
                  onclick={cancelDeletion}
                  class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto"
                >
                  Cancel
                </button>
              </div>
            
            {:else if deletionStep === 2}
              <!-- Step 2: Final Confirmation -->
              <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
                <div class="sm:flex sm:items-start">
                  <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                    <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                    </svg>
                  </div>
                  <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left w-full">
                    <h3 class="text-lg font-semibold leading-6 text-gray-900">
                      Final Confirmation
                    </h3>
                    
                    <div class="mt-4">
                      <p class="text-sm text-gray-500 mb-4">
                        To confirm deletion, please type the username <strong>{user?.username}</strong> in the field below:
                      </p>
                      
                      <input
                        type="text"
                        bind:value={usernameConfirmation}
                        placeholder="Enter username to confirm"
                        class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6"
                      />
                      
                      <div class="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg">
                        <p class="text-sm text-red-800">
                          This will permanently delete all user data and cannot be undone.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                <button
                  type="button"
                  onclick={confirmDeletion}
                  disabled={isSaving || usernameConfirmation !== user?.username}
                  class="inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {#if isSaving}
                    Deleting...
                  {:else}
                    Delete User
                  {/if}
                </button>
                <button
                  type="button"
                  onclick={() => deletionStep = 1}
                  disabled={isSaving}
                  class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto disabled:opacity-50"
                >
                  Back
                </button>
              </div>
            {/if}
            
          </div>
        </div>
      </div>
    </div>
  {/if}
</RouteGuard>

// frontend-next/src/app/(main)/admin/users/[id]/page.tsx
'use client';

import { useState, useEffect, useMemo } from 'react';
import Link from 'next/link';
import { useRouter, useParams } from 'next/navigation';
import { useAuth } from '@/providers';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Skeleton } from '@/components/ui/skeleton';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { toast } from 'sonner';
import { ArrowLeft, AlertCircle, Loader2, Check, Eye, EyeOff, AlertTriangle, Trash2 } from 'lucide-react';
import * as adminApi from '@/api/admin';
import type { AdminUser, UserDeletionImpact } from '@/types';

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function UserStatusBadges({ user }: { user: AdminUser }) {
  return (
    <div className="flex flex-wrap gap-1">
      {user.isAdmin && (
        <Badge className="bg-purple-100 text-purple-800 hover:bg-purple-200">Admin</Badge>
      )}
      {!user.isActive ? (
        <Badge variant="destructive">Inactive</Badge>
      ) : !user.isAdmin ? (
        <Badge className="bg-green-100 text-green-800 hover:bg-green-200">User</Badge>
      ) : null}
    </div>
  );
}

function EditUserSkeleton() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Skeleton className="h-6 w-6" />
        <div>
          <Skeleton className="h-8 w-64 mb-2" />
          <Skeleton className="h-4 w-96" />
        </div>
      </div>
      <Card className="max-w-2xl">
        <CardHeader>
          <Skeleton className="h-6 w-40" />
        </CardHeader>
        <CardContent className="space-y-6">
          <Skeleton className="h-16 w-full" />
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-10 w-32" />
        </CardContent>
      </Card>
    </div>
  );
}

export default function EditUserPage() {
  const router = useRouter();
  const params = useParams();
  const userId = params.id as string;
  const { user: currentUser } = useAuth();

  const [user, setUser] = useState<AdminUser | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  // Form state
  const [formData, setFormData] = useState({
    username: '',
    isActive: true,
    isAdmin: false,
  });
  const [originalData, setOriginalData] = useState({
    username: '',
    isActive: true,
    isAdmin: false,
  });

  // Password reset state
  const [showPasswordReset, setShowPasswordReset] = useState(false);
  const [newPassword, setNewPassword] = useState('');
  const [showNewPassword, setShowNewPassword] = useState(false);

  // Delete state
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [deletionStep, setDeletionStep] = useState(1);
  const [deletionImpact, setDeletionImpact] = useState<UserDeletionImpact | null>(null);
  const [isDeletionImpactLoading, setIsDeletionImpactLoading] = useState(false);
  const [usernameConfirmation, setUsernameConfirmation] = useState('');

  // Derived values
  const isEditingSelf = useMemo(() => currentUser?.id === userId, [currentUser, userId]);
  const hasChanges = useMemo(
    () =>
      formData.username !== originalData.username ||
      formData.isActive !== originalData.isActive ||
      formData.isAdmin !== originalData.isAdmin,
    [formData, originalData]
  );

  // Check admin access
  useEffect(() => {
    if (currentUser && !currentUser.isAdmin) {
      router.replace('/dashboard');
    }
  }, [currentUser, router]);

  // Fetch user
  useEffect(() => {
    const fetchUser = async () => {
      try {
        setIsLoading(true);
        setError(null);
        const fetchedUser = await adminApi.getUserById(userId);
        setUser(fetchedUser);
        const data = {
          username: fetchedUser.username,
          isActive: fetchedUser.isActive,
          isAdmin: fetchedUser.isAdmin,
        };
        setFormData(data);
        setOriginalData(data);
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Failed to fetch user';
        setError(errorMessage);
      } finally {
        setIsLoading(false);
      }
    };

    if (currentUser?.isAdmin && userId) {
      fetchUser();
    }
  }, [currentUser, userId]);

  // Handle save
  const handleSave = async () => {
    if (!user || !hasChanges) return;

    // Validate form
    if (!formData.username.trim()) {
      setError('Username is required');
      return;
    }

    // Check for self-modification restrictions
    if (isEditingSelf) {
      if (!formData.isActive) {
        setError('You cannot deactivate your own account');
        return;
      }
      if (!formData.isAdmin) {
        setError('You cannot remove your own admin privileges');
        return;
      }
    }

    try {
      setIsSaving(true);
      setError(null);
      setSuccessMessage(null);

      const updatedUser = await adminApi.updateUser(user.id, {
        username: formData.username.trim(),
        is_active: formData.isActive,
        is_admin: formData.isAdmin,
      });

      setUser(updatedUser);
      const data = {
        username: updatedUser.username,
        isActive: updatedUser.isActive,
        isAdmin: updatedUser.isAdmin,
      };
      setFormData(data);
      setOriginalData(data);
      setSuccessMessage('User updated successfully');
      toast.success('User updated successfully');

      setTimeout(() => setSuccessMessage(null), 3000);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to update user';
      setError(errorMessage);
    } finally {
      setIsSaving(false);
    }
  };

  // Handle password reset
  const handlePasswordReset = async () => {
    if (!user || !newPassword.trim()) return;

    try {
      setIsSaving(true);
      setError(null);

      await adminApi.resetUserPassword(user.id, newPassword.trim());

      setSuccessMessage('Password reset successfully. User will need to log in again.');
      toast.success('Password reset successfully');
      setNewPassword('');
      setShowPasswordReset(false);

      setTimeout(() => setSuccessMessage(null), 5000);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to reset password';
      setError(errorMessage);
    } finally {
      setIsSaving(false);
    }
  };

  // Handle delete
  const startDeletion = async () => {
    if (!user) return;

    setShowDeleteDialog(true);
    setDeletionStep(1);
    setUsernameConfirmation('');

    try {
      setIsDeletionImpactLoading(true);
      const impact = await adminApi.getUserDeletionImpact(user.id);
      setDeletionImpact(impact);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to get deletion impact';
      setError(errorMessage);
      setShowDeleteDialog(false);
    } finally {
      setIsDeletionImpactLoading(false);
    }
  };

  const confirmDeletion = async () => {
    if (!user || !deletionImpact || usernameConfirmation !== user.username) return;

    try {
      setIsSaving(true);
      await adminApi.deleteUser(user.id);
      toast.success('User deleted successfully');
      router.push('/admin/users');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to delete user';
      setError(errorMessage);
      setIsSaving(false);
    }
  };

  const cancelDeletion = () => {
    setShowDeleteDialog(false);
    setDeletionStep(1);
    setDeletionImpact(null);
    setUsernameConfirmation('');
  };

  const resetForm = () => {
    setFormData({ ...originalData });
    setError(null);
    setSuccessMessage(null);
  };

  // Show loading state
  if (!currentUser?.isAdmin) {
    return null;
  }

  if (isLoading) {
    return <EditUserSkeleton />;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link href="/admin/users" aria-label="Back to users">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <h1 className="text-2xl font-bold">
            {user ? `Edit User: ${user.username}` : 'User Not Found'}
          </h1>
          {user && (
            <p className="text-muted-foreground">
              User ID: {user.id} - Created {formatDate(user.createdAt)}
              {isEditingSelf && (
                <span className="ml-2 text-primary font-medium">(This is you)</span>
              )}
            </p>
          )}
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription className="flex items-center justify-between">
            <span>{error}</span>
            <Button variant="outline" size="sm" onClick={() => setError(null)}>
              Dismiss
            </Button>
          </AlertDescription>
        </Alert>
      )}

      {/* Success Alert */}
      {successMessage && (
        <Alert className="border-green-500 bg-green-50 text-green-800">
          <Check className="h-4 w-4" />
          <AlertDescription>{successMessage}</AlertDescription>
        </Alert>
      )}

      {user ? (
        <div className="grid gap-6 lg:grid-cols-2">
          {/* User Information Card */}
          <Card>
            <CardHeader>
              <CardTitle>User Information</CardTitle>
              <CardDescription>Edit user details and permissions</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Current Status Display */}
              <div className="p-4 bg-muted/50 rounded-lg">
                <div className="flex items-center gap-4">
                  <div className="h-12 w-12 rounded-full bg-muted flex items-center justify-center">
                    <span className="text-lg font-medium">
                      {user.username.charAt(0).toUpperCase()}
                    </span>
                  </div>
                  <div>
                    <p className="font-medium text-lg">{user.username}</p>
                    <UserStatusBadges user={user} />
                    <p className="text-sm text-muted-foreground mt-1">
                      Last updated {formatDate(user.updatedAt)}
                    </p>
                  </div>
                </div>
              </div>

              {/* Username Input */}
              <div>
                <Label htmlFor="username">Username</Label>
                <Input
                  id="username"
                  value={formData.username}
                  onChange={(e) => setFormData((prev) => ({ ...prev, username: e.target.value }))}
                  className="mt-1"
                />
              </div>

              {/* Account Status */}
              <div className="space-y-4">
                <Label>Account Status</Label>

                <div className="flex items-center space-x-3">
                  <Checkbox
                    id="isActive"
                    checked={formData.isActive}
                    onCheckedChange={(checked) =>
                      setFormData((prev) => ({ ...prev, isActive: checked === true }))
                    }
                    disabled={isEditingSelf}
                  />
                  <label
                    htmlFor="isActive"
                    className={`text-sm ${isEditingSelf ? 'text-muted-foreground' : ''}`}
                  >
                    Account is active
                    {isEditingSelf && (
                      <span className="text-xs ml-2">(Cannot modify your own account status)</span>
                    )}
                  </label>
                </div>

                <div className="flex items-center space-x-3">
                  <Checkbox
                    id="isAdmin"
                    checked={formData.isAdmin}
                    onCheckedChange={(checked) =>
                      setFormData((prev) => ({ ...prev, isAdmin: checked === true }))
                    }
                    disabled={isEditingSelf}
                  />
                  <label
                    htmlFor="isAdmin"
                    className={`text-sm ${isEditingSelf ? 'text-muted-foreground' : ''}`}
                  >
                    Administrator privileges
                    {isEditingSelf && (
                      <span className="text-xs ml-2">(Cannot modify your own admin privileges)</span>
                    )}
                  </label>
                </div>
              </div>

              {/* Form Actions */}
              <div className="flex gap-3 pt-4 border-t">
                <Button onClick={handleSave} disabled={!hasChanges || isSaving}>
                  {isSaving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  Save Changes
                </Button>
                <Button variant="outline" onClick={resetForm} disabled={!hasChanges || isSaving}>
                  Reset
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Account Actions Card */}
          <Card>
            <CardHeader>
              <CardTitle>Account Actions</CardTitle>
              <CardDescription>Password reset and account deletion</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Password Reset */}
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2">Reset Password</h4>
                <p className="text-sm text-muted-foreground mb-4">
                  Generate a new password for this user. They will need to log in again with the new
                  password.
                </p>

                {showPasswordReset ? (
                  <div className="space-y-3">
                    <div>
                      <Label htmlFor="newPassword">New Password</Label>
                      <div className="relative mt-1">
                        <Input
                          id="newPassword"
                          type={showNewPassword ? 'text' : 'password'}
                          value={newPassword}
                          onChange={(e) => setNewPassword(e.target.value)}
                          placeholder="Enter new password"
                          className="pr-10"
                        />
                        <button
                          type="button"
                          onClick={() => setShowNewPassword(!showNewPassword)}
                          className="absolute inset-y-0 right-0 flex items-center pr-3"
                          aria-label={showNewPassword ? 'Hide password' : 'Show password'}
                        >
                          {showNewPassword ? (
                            <EyeOff className="h-4 w-4 text-muted-foreground" />
                          ) : (
                            <Eye className="h-4 w-4 text-muted-foreground" />
                          )}
                        </button>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <Button
                        variant="secondary"
                        onClick={handlePasswordReset}
                        disabled={!newPassword.trim() || isSaving}
                      >
                        {isSaving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                        Reset Password
                      </Button>
                      <Button
                        variant="outline"
                        onClick={() => {
                          setShowPasswordReset(false);
                          setNewPassword('');
                        }}
                        disabled={isSaving}
                      >
                        Cancel
                      </Button>
                    </div>
                  </div>
                ) : (
                  <Button variant="secondary" onClick={() => setShowPasswordReset(true)}>
                    Reset Password
                  </Button>
                )}
              </div>

              {/* Delete User */}
              {!isEditingSelf && (
                <div className="border border-destructive/50 rounded-lg p-4">
                  <h4 className="font-medium text-destructive mb-2">Delete User</h4>
                  <p className="text-sm text-destructive/80 mb-4">
                    Permanently delete this user account and all associated data. This action cannot
                    be undone.
                  </p>
                  <Button variant="destructive" onClick={startDeletion} disabled={isSaving}>
                    <Trash2 className="mr-2 h-4 w-4" />
                    Delete User
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      ) : (
        /* User Not Found */
        <Card className="max-w-md">
          <CardContent className="pt-6">
            <div className="text-center py-12">
              <h3 className="text-lg font-medium mb-2">User Not Found</h3>
              <p className="text-muted-foreground mb-4">
                The user with ID &quot;{userId}&quot; could not be found.
              </p>
              <Button asChild>
                <Link href="/admin/users">Back to Users</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          {deletionStep === 1 ? (
            <>
              <AlertDialogHeader>
                <AlertDialogTitle className="flex items-center gap-2">
                  <AlertTriangle className="h-5 w-5 text-destructive" />
                  Delete User: {user?.username}
                </AlertDialogTitle>
                <AlertDialogDescription asChild>
                  <div className="space-y-4">
                    {isDeletionImpactLoading ? (
                      <div className="flex justify-center py-4">
                        <Loader2 className="h-8 w-8 animate-spin text-destructive" />
                      </div>
                    ) : deletionImpact ? (
                      <>
                        <p>This action will permanently delete the following data:</p>
                        <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4 space-y-2 text-sm">
                          <div className="flex justify-between">
                            <span>Games in collection:</span>
                            <span className="font-medium text-destructive">
                              {deletionImpact.total_games}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span>User-created tags:</span>
                            <span className="font-medium text-destructive">
                              {deletionImpact.total_tags}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span>Wishlist items:</span>
                            <span className="font-medium text-destructive">
                              {deletionImpact.total_wishlist_items}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span>Import jobs:</span>
                            <span className="font-medium text-destructive">
                              {deletionImpact.total_import_jobs}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span>Active sessions:</span>
                            <span className="font-medium text-destructive">
                              {deletionImpact.total_sessions}
                            </span>
                          </div>
                        </div>
                        <Alert>
                          <AlertTriangle className="h-4 w-4" />
                          <AlertDescription>{deletionImpact.warning}</AlertDescription>
                        </Alert>
                      </>
                    ) : null}
                  </div>
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel onClick={cancelDeletion}>Cancel</AlertDialogCancel>
                <Button
                  variant="destructive"
                  onClick={() => setDeletionStep(2)}
                  disabled={isDeletionImpactLoading || !deletionImpact}
                >
                  Continue
                </Button>
              </AlertDialogFooter>
            </>
          ) : (
            <>
              <AlertDialogHeader>
                <AlertDialogTitle>Final Confirmation</AlertDialogTitle>
                <AlertDialogDescription asChild>
                  <div className="space-y-4">
                    <p>
                      To confirm deletion, please type the username{' '}
                      <strong>{user?.username}</strong> in the field below:
                    </p>
                    <Input
                      value={usernameConfirmation}
                      onChange={(e) => setUsernameConfirmation(e.target.value)}
                      placeholder="Enter username to confirm"
                    />
                    <Alert variant="destructive">
                      <AlertTriangle className="h-4 w-4" />
                      <AlertDescription>
                        This will permanently delete all user data and cannot be undone.
                      </AlertDescription>
                    </Alert>
                  </div>
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel onClick={() => setDeletionStep(1)}>Back</AlertDialogCancel>
                <AlertDialogAction
                  onClick={confirmDeletion}
                  disabled={isSaving || usernameConfirmation !== user?.username}
                  className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                >
                  {isSaving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  Delete User
                </AlertDialogAction>
              </AlertDialogFooter>
            </>
          )}
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
