// frontend-next/src/app/(main)/tags/page.tsx
'use client';

import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  Tag as TagIcon,
  Plus,
  Search,
  ArrowUpDown,
  Pencil,
  Trash2,
  Loader2,
  CheckCircle,
  XCircle,
  BarChart3,
  TrendingUp,
} from 'lucide-react';
import { useAllTags, useCreateTag, useUpdateTag, useDeleteTag } from '@/hooks';
import type { Tag } from '@/types';

type SortField = 'name' | 'usage' | 'created';
type SortOrder = 'asc' | 'desc';

// Predefined color palette for tags
const COLOR_PALETTE = [
  '#EF4444', // red
  '#F97316', // orange
  '#F59E0B', // amber
  '#EAB308', // yellow
  '#84CC16', // lime
  '#22C55E', // green
  '#10B981', // emerald
  '#14B8A6', // teal
  '#06B6D4', // cyan
  '#0EA5E9', // sky
  '#3B82F6', // blue
  '#6366F1', // indigo
  '#8B5CF6', // violet
  '#A855F7', // purple
  '#D946EF', // fuchsia
  '#EC4899', // pink
  '#F43F5E', // rose
  '#6B7280', // gray
];

function ColorPicker({
  value,
  onChange,
}: {
  value: string;
  onChange: (color: string) => void;
}) {
  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2">
        <div
          className="h-8 w-8 rounded-md border"
          style={{ backgroundColor: value }}
        />
        <Input
          type="text"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="w-28 font-mono text-sm"
          placeholder="#000000"
        />
      </div>
      <div className="grid grid-cols-9 gap-1">
        {COLOR_PALETTE.map((color) => (
          <button
            key={color}
            type="button"
            className={`h-6 w-6 rounded-md border-2 transition-transform hover:scale-110 ${
              value === color ? 'border-foreground' : 'border-transparent'
            }`}
            style={{ backgroundColor: color }}
            onClick={() => onChange(color)}
            aria-label={`Select color ${color}`}
          />
        ))}
      </div>
    </div>
  );
}

function TagsPageSkeleton() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <Skeleton className="mb-2 h-8 w-48" />
          <Skeleton className="h-4 w-96" />
        </div>
        <Skeleton className="h-10 w-32" />
      </div>
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-5">
        {[1, 2, 3, 4, 5].map((i) => (
          <Skeleton key={i} className="h-24" />
        ))}
      </div>
      <Card>
        <CardContent className="pt-6">
          <div className="flex gap-4">
            <Skeleton className="h-10 flex-1" />
            <Skeleton className="h-10 w-40" />
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="pt-6">
          <div className="space-y-4">
            {[1, 2, 3, 4, 5].map((i) => (
              <div key={i} className="flex items-center gap-4">
                <Skeleton className="h-6 w-6 rounded-full" />
                <Skeleton className="h-4 flex-1" />
                <Skeleton className="h-6 w-16" />
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

interface TagFormData {
  name: string;
  color: string;
  description: string;
}

const initialFormData: TagFormData = {
  name: '',
  color: '#6B7280',
  description: '',
};

export default function TagsPage() {
  const router = useRouter();
  const { data: tags, isLoading, error, refetch } = useAllTags();
  const createTagMutation = useCreateTag();
  const updateTagMutation = useUpdateTag();
  const deleteTagMutation = useDeleteTag();

  // UI State
  const [searchQuery, setSearchQuery] = useState('');
  const [sortField, setSortField] = useState<SortField>('name');
  const [sortOrder, setSortOrder] = useState<SortOrder>('asc');

  // Modal State
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [showEditDialog, setShowEditDialog] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [selectedTag, setSelectedTag] = useState<Tag | null>(null);
  const [formData, setFormData] = useState<TagFormData>(initialFormData);

  // Computed stats
  const stats = useMemo(() => {
    if (!tags) return { total: 0, used: 0, unused: 0, totalUsage: 0, avgUsage: '0' };
    const total = tags.length;
    const used = tags.filter((t) => (t.game_count ?? 0) > 0).length;
    const unused = total - used;
    const totalUsage = tags.reduce((sum, t) => sum + (t.game_count ?? 0), 0);
    const avgUsage = total > 0 ? (totalUsage / total).toFixed(1) : '0';
    return { total, used, unused, totalUsage, avgUsage };
  }, [tags]);

  // Filtered and sorted tags
  const filteredTags = useMemo(() => {
    if (!tags) return [];
    let result = [...tags];

    // Filter by search
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      result = result.filter(
        (tag) =>
          tag.name.toLowerCase().includes(query) ||
          tag.description?.toLowerCase().includes(query)
      );
    }

    // Sort
    result.sort((a, b) => {
      let comparison = 0;
      switch (sortField) {
        case 'name':
          comparison = a.name.localeCompare(b.name);
          break;
        case 'usage':
          comparison = (a.game_count ?? 0) - (b.game_count ?? 0);
          break;
        case 'created':
          comparison = new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
          break;
      }
      return sortOrder === 'asc' ? comparison : -comparison;
    });

    return result;
  }, [tags, searchQuery, sortField, sortOrder]);

  // Suggest a color not yet used
  const suggestColor = () => {
    if (!tags) return COLOR_PALETTE[0];
    const usedColors = new Set(tags.map((t) => t.color));
    return COLOR_PALETTE.find((c) => !usedColors.has(c)) ?? COLOR_PALETTE[0];
  };

  // Handlers
  const handleTagClick = (tag: Tag) => {
    router.push(`/games?tag=${tag.id}`);
  };

  const handleOpenCreate = () => {
    setFormData({ ...initialFormData, color: suggestColor() });
    setShowCreateDialog(true);
  };

  const handleOpenEdit = (tag: Tag) => {
    setSelectedTag(tag);
    setFormData({
      name: tag.name,
      color: tag.color,
      description: tag.description ?? '',
    });
    setShowEditDialog(true);
  };

  const handleOpenDelete = (tag: Tag) => {
    setSelectedTag(tag);
    setShowDeleteDialog(true);
  };

  const handleCreate = async () => {
    if (!formData.name.trim()) {
      toast.error('Tag name is required');
      return;
    }

    try {
      await createTagMutation.mutateAsync({
        name: formData.name.trim(),
        color: formData.color,
        description: formData.description.trim() || undefined,
      });
      toast.success('Tag created successfully');
      setShowCreateDialog(false);
      setFormData(initialFormData);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to create tag';
      toast.error(message);
    }
  };

  const handleUpdate = async () => {
    if (!selectedTag || !formData.name.trim()) {
      toast.error('Tag name is required');
      return;
    }

    try {
      await updateTagMutation.mutateAsync({
        id: selectedTag.id,
        data: {
          name: formData.name.trim(),
          color: formData.color,
          description: formData.description.trim() || undefined,
        },
      });
      toast.success('Tag updated successfully');
      setShowEditDialog(false);
      setSelectedTag(null);
      setFormData(initialFormData);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to update tag';
      toast.error(message);
    }
  };

  const handleDelete = async () => {
    if (!selectedTag) return;

    try {
      await deleteTagMutation.mutateAsync(selectedTag.id);
      toast.success('Tag deleted successfully');
      setShowDeleteDialog(false);
      setSelectedTag(null);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to delete tag';
      toast.error(message);
    }
  };

  const toggleSort = (field: SortField) => {
    if (sortField === field) {
      setSortOrder((prev) => (prev === 'asc' ? 'desc' : 'asc'));
    } else {
      setSortField(field);
      setSortOrder('asc');
    }
  };

  if (isLoading) {
    return <TagsPageSkeleton />;
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <XCircle className="h-12 w-12 text-destructive" />
        <h2 className="mt-4 text-lg font-semibold">Failed to load tags</h2>
        <p className="text-muted-foreground">{error.message}</p>
        <Button onClick={() => refetch()} className="mt-4">
          Try Again
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="flex items-center gap-2 text-2xl font-bold">
            <TagIcon className="h-6 w-6" />
            Tag Management
          </h1>
          <p className="text-muted-foreground">
            Organize your games with custom tags. Click any tag to see games with that tag.
          </p>
        </div>
        <Button onClick={handleOpenCreate}>
          <Plus className="mr-2 h-4 w-4" />
          Create Tag
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-5">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <TagIcon className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-sm text-muted-foreground">Total Tags</p>
                <p className="text-2xl font-bold">{stats.total}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <CheckCircle className="h-5 w-5 text-green-500" />
              <div>
                <p className="text-sm text-muted-foreground">Used Tags</p>
                <p className="text-2xl font-bold">{stats.used}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <XCircle className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-sm text-muted-foreground">Unused Tags</p>
                <p className="text-2xl font-bold">{stats.unused}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <BarChart3 className="h-5 w-5 text-blue-500" />
              <div>
                <p className="text-sm text-muted-foreground">Total Usage</p>
                <p className="text-2xl font-bold">{stats.totalUsage}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <TrendingUp className="h-5 w-5 text-purple-500" />
              <div>
                <p className="text-sm text-muted-foreground">Avg per Tag</p>
                <p className="text-2xl font-bold">{stats.avgUsage}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search and Sort Controls */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Search tags..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9"
              />
            </div>
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">Sort by:</span>
              <div className="flex rounded-md border">
                <Button
                  variant={sortField === 'name' ? 'secondary' : 'ghost'}
                  size="sm"
                  className="rounded-r-none"
                  onClick={() => toggleSort('name')}
                >
                  Name
                  {sortField === 'name' && (
                    <ArrowUpDown className="ml-1 h-3 w-3" />
                  )}
                </Button>
                <Button
                  variant={sortField === 'usage' ? 'secondary' : 'ghost'}
                  size="sm"
                  className="rounded-none border-x"
                  onClick={() => toggleSort('usage')}
                >
                  Usage
                  {sortField === 'usage' && (
                    <ArrowUpDown className="ml-1 h-3 w-3" />
                  )}
                </Button>
                <Button
                  variant={sortField === 'created' ? 'secondary' : 'ghost'}
                  size="sm"
                  className="rounded-l-none"
                  onClick={() => toggleSort('created')}
                >
                  Date
                  {sortField === 'created' && (
                    <ArrowUpDown className="ml-1 h-3 w-3" />
                  )}
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Tags List */}
      <Card>
        <CardHeader>
          <CardTitle>Tags ({filteredTags.length})</CardTitle>
          <CardDescription>Click a tag to view games with that tag</CardDescription>
        </CardHeader>
        <CardContent>
          {filteredTags.length === 0 ? (
            <div className="py-12 text-center">
              {searchQuery ? (
                <>
                  <Search className="mx-auto h-12 w-12 text-muted-foreground" />
                  <h3 className="mt-2 font-medium">No tags found</h3>
                  <p className="text-sm text-muted-foreground">
                    No tags match your search &quot;{searchQuery}&quot;
                  </p>
                </>
              ) : (
                <>
                  <TagIcon className="mx-auto h-12 w-12 text-muted-foreground" />
                  <h3 className="mt-2 font-medium">No tags</h3>
                  <p className="text-sm text-muted-foreground">
                    Get started by creating your first tag to organize your games.
                  </p>
                  <Button onClick={handleOpenCreate} className="mt-4">
                    Create Your First Tag
                  </Button>
                </>
              )}
            </div>
          ) : (
            <div className="divide-y">
              {filteredTags.map((tag) => (
                <div
                  key={tag.id}
                  className="flex items-center justify-between py-4 transition-colors hover:bg-muted/50"
                >
                  <button
                    type="button"
                    className="flex flex-1 items-center gap-4 text-left"
                    onClick={() => handleTagClick(tag)}
                  >
                    <div
                      className="h-6 w-6 shrink-0 rounded-full border"
                      style={{ backgroundColor: tag.color }}
                    />
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="font-medium">{tag.name}</span>
                        {(tag.game_count ?? 0) > 0 ? (
                          <span className="rounded-full bg-muted px-2 py-0.5 text-xs">
                            {tag.game_count} game{tag.game_count !== 1 ? 's' : ''}
                          </span>
                        ) : (
                          <span className="rounded-full bg-muted/50 px-2 py-0.5 text-xs text-muted-foreground">
                            Unused
                          </span>
                        )}
                      </div>
                      {tag.description && (
                        <p className="truncate text-sm text-muted-foreground">
                          {tag.description}
                        </p>
                      )}
                      <p className="text-xs text-muted-foreground">
                        Created {new Date(tag.created_at).toLocaleDateString()}
                      </p>
                    </div>
                  </button>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleOpenEdit(tag)}
                    >
                      <Pencil className="h-4 w-4" />
                      <span className="sr-only">Edit</span>
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleOpenDelete(tag)}
                    >
                      <Trash2 className="h-4 w-4 text-destructive" />
                      <span className="sr-only">Delete</span>
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Create Tag Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create New Tag</DialogTitle>
            <DialogDescription>
              Create a new tag to organize your games.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="tag-name">Name *</Label>
              <Input
                id="tag-name"
                value={formData.name}
                onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
                placeholder="Enter tag name..."
                maxLength={100}
              />
            </div>
            <div className="space-y-2">
              <Label>Color</Label>
              <ColorPicker
                value={formData.color}
                onChange={(color) => setFormData((prev) => ({ ...prev, color }))}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="tag-description">Description</Label>
              <Input
                id="tag-description"
                value={formData.description}
                onChange={(e) =>
                  setFormData((prev) => ({ ...prev, description: e.target.value }))
                }
                placeholder="Optional description..."
                maxLength={500}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleCreate} disabled={createTagMutation.isPending}>
              {createTagMutation.isPending && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              )}
              Create Tag
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Tag Dialog */}
      <Dialog open={showEditDialog} onOpenChange={setShowEditDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Tag</DialogTitle>
            <DialogDescription>Update the tag details.</DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="edit-tag-name">Name *</Label>
              <Input
                id="edit-tag-name"
                value={formData.name}
                onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
                placeholder="Enter tag name..."
                maxLength={100}
              />
            </div>
            <div className="space-y-2">
              <Label>Color</Label>
              <ColorPicker
                value={formData.color}
                onChange={(color) => setFormData((prev) => ({ ...prev, color }))}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="edit-tag-description">Description</Label>
              <Input
                id="edit-tag-description"
                value={formData.description}
                onChange={(e) =>
                  setFormData((prev) => ({ ...prev, description: e.target.value }))
                }
                placeholder="Optional description..."
                maxLength={500}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowEditDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdate} disabled={updateTagMutation.isPending}>
              {updateTagMutation.isPending && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              )}
              Update Tag
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Tag</AlertDialogTitle>
            <AlertDialogDescription>
              {selectedTag && (selectedTag.game_count ?? 0) > 0
                ? `Delete "${selectedTag.name}"? This will remove it from ${selectedTag.game_count} game${selectedTag.game_count !== 1 ? 's' : ''}.`
                : `Delete "${selectedTag?.name}"?`}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {deleteTagMutation.isPending && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              )}
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// frontend/src/routes/tags/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { tags, ui, type Tag } from '$lib/stores';
  import { ColorPicker } from '$lib/components/tags';

  let isLoading = $state(false);
  let showCreateModal = $state(false);
  let showEditModal = $state(false);
  let selectedTag = $state<Tag | null>(null);

  // Create tag form
  let createForm = $state({
    name: '',
    color: '#6B7280',
    description: ''
  });

  // Edit tag form
  let editForm = $state({
    name: '',
    color: '#6B7280', 
    description: ''
  });

  let sortBy = $state<'name' | 'usage' | 'created'>('name');
  let sortOrder = $state<'asc' | 'desc'>('asc');
  let searchQuery = $state('');

  // Computed values
  const sortedTags = $derived.by(() => {
    let filtered = tags.value.tags;

    // Apply search filter
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(tag => 
        tag.name.toLowerCase().includes(query) ||
        tag.description?.toLowerCase().includes(query)
      );
    }

    // Apply sorting (create new array to avoid mutation)
    return [...filtered].sort((a, b) => {
      let comparison = 0;
      
      switch (sortBy) {
        case 'name':
          comparison = a.name.localeCompare(b.name);
          break;
        case 'usage':
          const aCount = a.game_count || 0;
          const bCount = b.game_count || 0;
          comparison = aCount - bCount;
          break;
        case 'created':
          comparison = new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
          break;
      }
      
      return sortOrder === 'asc' ? comparison : -comparison;
    });
  });

  const tagStats = $derived.by(() => {
    const totalTags = tags.value.tags.length;
    const usedTags = tags.value.tags.filter(tag => (tag.game_count || 0) > 0).length;
    const unusedTags = totalTags - usedTags;
    const totalUsage = tags.value.tags.reduce((sum, tag) => sum + (tag.game_count || 0), 0);
    
    return {
      total: totalTags,
      used: usedTags,
      unused: unusedTags,
      totalUsage,
      averageUsage: totalTags > 0 ? (totalUsage / totalTags).toFixed(1) : 0
    };
  });

  onMount(async () => {
    // Load tags if not already loaded
    if (tags.value.tags.length === 0 && !tags.value.isLoading) {
      await loadTags();
    }
  });

  const loadTags = async () => {
    isLoading = true;
    try {
      await tags.fetchTags();
      
      // Try to get usage stats, but don't fail if it doesn't work
      try {
        await tags.getTagUsageStats();
      } catch (statsError) {
        // Don't fail the whole operation if usage stats fail
        console.warn('Tag usage stats failed, but tags loaded successfully');
      }
    } catch (error) {
      ui.addNotification({ title: 'Error', message: 'Failed to load tags', type: 'error' });
    } finally {
      isLoading = false;
    }
  };

  const handleTagClick = (tag: Tag) => {
    // Navigate to games page with tag filter
    goto(`/games?tag=${tag.id}`);
  };

  const openCreateModal = () => {
    createForm = {
      name: '',
      color: tags.suggestColor() || '#6B7280',
      description: ''
    };
    showCreateModal = true;
  };

  const openEditModal = (tag: Tag) => {
    selectedTag = tag;
    editForm = {
      name: tag.name,
      color: tag.color,
      description: tag.description || ''
    };
    showEditModal = true;
  };

  const closeModals = () => {
    showCreateModal = false;
    showEditModal = false;
    selectedTag = null;
  };

  const createTag = async () => {
    if (!createForm.name.trim()) {
      ui.addNotification({ title: 'Notification', message: 'Tag name is required', type: 'error' });
      return;
    }

    try {
      const tagData = {
        name: createForm.name.trim(),
        color: createForm.color,
        ...(createForm.description.trim() && { description: createForm.description.trim() })
      };
      await tags.createTag(tagData);
      
      ui.addNotification({ title: 'Notification', message: 'Tag created successfully', type: 'success' });
      closeModals();
      await loadTags(); // Refresh to get usage stats
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to create tag';
      ui.addNotification({ title: 'Error', message, type: 'error' });
    }
  };

  const updateTag = async () => {
    if (!selectedTag || !editForm.name.trim()) {
      ui.addNotification({ title: 'Notification', message: 'Tag name is required', type: 'error' });
      return;
    }

    try {
      const updateData = {
        name: editForm.name.trim(),
        color: editForm.color,
        ...(editForm.description.trim() && { description: editForm.description.trim() })
      };
      await tags.updateTag(selectedTag.id, updateData);
      
      ui.addNotification({ title: 'Notification', message: 'Tag updated successfully', type: 'success' });
      closeModals();
      await loadTags(); // Refresh to get usage stats
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to update tag';
      ui.addNotification({ title: 'Error', message, type: 'error' });
    }
  };

  const deleteTag = async (tag: Tag) => {
    const confirmMessage = tag.game_count && tag.game_count > 0
      ? `Delete "${tag.name}"? This will remove it from ${tag.game_count} game${tag.game_count !== 1 ? 's' : ''}.`
      : `Delete "${tag.name}"?`;
      
    if (!confirm(confirmMessage)) return;

    try {
      await tags.deleteTag(tag.id);
      ui.addNotification({ title: 'Notification', message: 'Tag deleted successfully', type: 'success' });
      await loadTags(); // Refresh to get updated stats
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to delete tag';
      ui.addNotification({ title: 'Error', message, type: 'error' });
    }
  };

  const changeSorting = (newSortBy: typeof sortBy) => {
    if (sortBy === newSortBy) {
      sortOrder = sortOrder === 'asc' ? 'desc' : 'asc';
    } else {
      sortBy = newSortBy;
      sortOrder = 'asc';
    }
  };

</script>

<svelte:head>
  <title>Manage Tags - Nexorious</title>
</svelte:head>

<!-- Page Header -->
<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
    <h1 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
      Tag Management
    </h1>
    <p class="mt-2 text-sm text-gray-700">
      Organize your games with custom tags. Click any tag to see games with that tag.
    </p>
  </div>
  <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
    <button
      type="button"
      class="btn-primary"
      onclick={openCreateModal}
    >
      Create Tag
    </button>
  </div>
</div>

<!-- Stats Cards -->
<div class="mt-8 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-5">
  <div class="bg-white overflow-hidden shadow rounded-lg">
    <div class="p-5">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <svg class="h-6 w-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.99 1.99 0 013 12V7a4 4 0 014-4z"/>
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm font-medium text-gray-500 truncate">Total Tags</dt>
            <dd class="text-lg font-medium text-gray-900">{tagStats.total}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="bg-white overflow-hidden shadow rounded-lg">
    <div class="p-5">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <svg class="h-6 w-6 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm font-medium text-gray-500 truncate">Used Tags</dt>
            <dd class="text-lg font-medium text-gray-900">{tagStats.used}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="bg-white overflow-hidden shadow rounded-lg">
    <div class="p-5">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <svg class="h-6 w-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H4"/>
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm font-medium text-gray-500 truncate">Unused Tags</dt>
            <dd class="text-lg font-medium text-gray-900">{tagStats.unused}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="bg-white overflow-hidden shadow rounded-lg">
    <div class="p-5">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <svg class="h-6 w-6 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"/>
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm font-medium text-gray-500 truncate">Total Usage</dt>
            <dd class="text-lg font-medium text-gray-900">{tagStats.totalUsage}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="bg-white overflow-hidden shadow rounded-lg">
    <div class="p-5">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <svg class="h-6 w-6 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm font-medium text-gray-500 truncate">Avg per Tag</dt>
            <dd class="text-lg font-medium text-gray-900">{tagStats.averageUsage}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Search and Sort Controls -->
<div class="mt-8 bg-white shadow rounded-lg">
  <div class="px-4 py-5 sm:p-6">
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="flex-1 max-w-lg">
        <input
          type="text"
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
          placeholder="Search tags..."
          bind:value={searchQuery}
        />
      </div>
      
      <div class="mt-4 sm:mt-0 sm:ml-4 flex items-center gap-4">
        <div class="flex items-center gap-2">
          <span class="text-sm text-gray-700">Sort by:</span>
          <div class="flex rounded-md shadow-sm">
            <button
              type="button"
              class="
                relative inline-flex items-center px-3 py-2 rounded-l-md border text-xs font-medium
                {sortBy === 'name' ? 'bg-primary-50 border-primary-500 text-primary-700' : 'bg-white border-gray-300 text-gray-700 hover:bg-gray-50'}
                focus:z-10 focus:outline-none focus:ring-1 focus:ring-primary-500 focus:border-primary-500
              "
              onclick={() => changeSorting('name')}
            >
              Name
              {#if sortBy === 'name'}
                <svg class="ml-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path d={sortOrder === 'asc' ? "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" : "M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"}/>
                </svg>
              {/if}
            </button>
            <button
              type="button"
              class="
                relative -ml-px inline-flex items-center px-3 py-2 border text-xs font-medium
                {sortBy === 'usage' ? 'bg-primary-50 border-primary-500 text-primary-700' : 'bg-white border-gray-300 text-gray-700 hover:bg-gray-50'}
                focus:z-10 focus:outline-none focus:ring-1 focus:ring-primary-500 focus:border-primary-500
              "
              onclick={() => changeSorting('usage')}
            >
              Usage
              {#if sortBy === 'usage'}
                <svg class="ml-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path d={sortOrder === 'asc' ? "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" : "M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"}/>
                </svg>
              {/if}
            </button>
            <button
              type="button"
              class="
                relative -ml-px inline-flex items-center px-3 py-2 rounded-r-md border text-xs font-medium
                {sortBy === 'created' ? 'bg-primary-50 border-primary-500 text-primary-700' : 'bg-white border-gray-300 text-gray-700 hover:bg-gray-50'}
                focus:z-10 focus:outline-none focus:ring-1 focus:ring-primary-500 focus:border-primary-500
              "
              onclick={() => changeSorting('created')}
            >
              Date
              {#if sortBy === 'created'}
                <svg class="ml-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path d={sortOrder === 'asc' ? "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" : "M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"}/>
                </svg>
              {/if}
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Tags List -->
<div class="mt-8">
  {#if isLoading}
    <div class="text-center py-12">
      <div class="inline-flex items-center text-lg text-gray-500">
        <svg class="animate-spin -ml-1 mr-3 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        Loading tags...
      </div>
    </div>
  {:else if sortedTags.length === 0}
    <div class="text-center py-12">
      {#if searchQuery}
        <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
        </svg>
        <h3 class="mt-2 text-sm font-medium text-gray-900">No tags found</h3>
        <p class="mt-1 text-sm text-gray-500">
          No tags match your search "{searchQuery}". Try a different search term.
        </p>
      {:else}
        <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.99 1.99 0 013 12V7a4 4 0 014-4z"/>
        </svg>
        <h3 class="mt-2 text-sm font-medium text-gray-900">No tags</h3>
        <p class="mt-1 text-sm text-gray-500">
          Get started by creating your first tag to organize your games.
        </p>
        <div class="mt-6">
          <button
            type="button"
            class="btn-primary"
            onclick={openCreateModal}
          >
            Create Your First Tag
          </button>
        </div>
      {/if}
    </div>
  {:else}
    <div class="bg-white shadow overflow-hidden sm:rounded-md">
      <ul class="divide-y divide-gray-200">
        {#each sortedTags as tag (tag.id)}
          <li class="hover:bg-gray-50 transition-colors duration-200">
            <div class="px-4 py-4 flex items-center justify-between">
              <button 
                type="button"
                class="flex items-center min-w-0 flex-1 cursor-pointer text-left bg-transparent border-none p-0 w-full" 
                onclick={() => handleTagClick(tag)}
                onkeydown={(event) => {
                  if (event.key === 'Enter' || event.key === ' ') {
                    event.preventDefault();
                    handleTagClick(tag);
                  }
                }}
                aria-label="View games with tag {tag.name}"
              >
                <!-- Tag Color -->
                <div 
                  class="h-6 w-6 rounded-full border border-gray-300 flex-shrink-0"
                  style="background-color: {tag.color}"
                ></div>
                
                <!-- Tag Info -->
                <div class="ml-4 min-w-0 flex-1">
                  <div class="flex items-center">
                    <p class="text-sm font-medium text-gray-900 truncate">{tag.name}</p>
                    {#if tag.game_count !== undefined && tag.game_count > 0}
                      <span class="ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                        {tag.game_count} game{tag.game_count !== 1 ? 's' : ''}
                      </span>
                    {:else}
                      <span class="ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-50 text-gray-500">
                        Unused
                      </span>
                    {/if}
                  </div>
                  {#if tag.description}
                    <p class="text-sm text-gray-500 truncate">{tag.description}</p>
                  {/if}
                  <p class="text-xs text-gray-400">
                    Created {new Date(tag.created_at).toLocaleDateString()}
                  </p>
                </div>
              </button>
              
              <!-- Actions -->
              <div class="flex items-center gap-2">
                <button
                  type="button"
                  class="text-primary-600 hover:text-primary-900 text-sm font-medium"
                  onclick={() => openEditModal(tag)}
                >
                  Edit
                </button>
                <button
                  type="button"
                  class="text-red-600 hover:text-red-900 text-sm font-medium"
                  onclick={() => deleteTag(tag)}
                >
                  Delete
                </button>
              </div>
            </div>
          </li>
        {/each}
      </ul>
    </div>
  {/if}
</div>

<!-- Create Tag Modal -->
{#if showCreateModal}
  <div class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
    <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
      <div class="mt-3">
        <h3 class="text-lg font-medium text-gray-900">Create New Tag</h3>
        <form class="mt-4 space-y-4" onsubmit={(e) => { e.preventDefault(); createTag(); }}>
          <div>
            <label for="tag-name" class="block text-sm font-medium text-gray-700">Name *</label>
            <input
              id="tag-name"
              type="text"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500"
              bind:value={createForm.name}
              placeholder="Enter tag name..."
              maxlength="100"
              required
            />
          </div>
          
          <div>
            <div class="block text-sm font-medium text-gray-700 mb-2">Color</div>
            <ColorPicker
              value={createForm.color}
              onchange={(color) => createForm.color = color}
            />
          </div>
          
          <div>
            <label for="tag-description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea
              id="tag-description"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500"
              bind:value={createForm.description}
              placeholder="Optional description..."
              rows="3"
              maxlength="500"
            ></textarea>
          </div>
          
          <div class="flex justify-end gap-3 pt-4">
            <button
              type="button"
              class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400"
              onclick={closeModals}
            >
              Cancel
            </button>
            <button
              type="submit"
              class="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700"
            >
              Create Tag
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{/if}

<!-- Edit Tag Modal -->
{#if showEditModal && selectedTag}
  <div class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
    <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
      <div class="mt-3">
        <h3 class="text-lg font-medium text-gray-900">Edit Tag</h3>
        <form class="mt-4 space-y-4" onsubmit={(e) => { e.preventDefault(); updateTag(); }}>
          <div>
            <label for="edit-tag-name" class="block text-sm font-medium text-gray-700">Name *</label>
            <input
              id="edit-tag-name"
              type="text"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500"
              bind:value={editForm.name}
              placeholder="Enter tag name..."
              maxlength="100"
              required
            />
          </div>
          
          <div>
            <div class="block text-sm font-medium text-gray-700 mb-2">Color</div>
            <ColorPicker
              value={editForm.color}
              onchange={(color) => editForm.color = color}
            />
          </div>
          
          <div>
            <label for="edit-tag-description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea
              id="edit-tag-description"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500"
              bind:value={editForm.description}
              placeholder="Optional description..."
              rows="3"
              maxlength="500"
            ></textarea>
          </div>
          
          <div class="flex justify-end gap-3 pt-4">
            <button
              type="button"
              class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400"
              onclick={closeModals}
            >
              Cancel
            </button>
            <button
              type="submit"
              class="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700"
            >
              Update Tag
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{/if}
