// ui/frontend/src/routes/_authenticated/admin/users/index.tsx
import { useState, useEffect, useMemo } from 'react';
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useAuth } from '@/providers';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { toast } from 'sonner';
import { Search, UserPlus, Users, AlertCircle, Loader2 } from 'lucide-react';
import * as adminApi from '@/api/admin';
import type { AdminUser } from '@/types';

export const Route = createFileRoute('/_authenticated/admin/users/')({
  component: AdminUsersPage,
});

type StatusFilter = 'all' | 'active' | 'inactive' | 'admin';

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function UserStatusBadges({ user }: { user: AdminUser }) {
  return (
    <div className="flex flex-wrap gap-1">
      {user.isAdmin && (
        <Badge className="bg-purple-100 text-purple-800 hover:bg-purple-200">Admin</Badge>
      )}
      {!user.isActive ? (
        <Badge variant="destructive">Inactive</Badge>
      ) : !user.isAdmin ? (
        <Badge className="bg-green-100 text-green-800 hover:bg-green-200">User</Badge>
      ) : null}
    </div>
  );
}

function UsersTableSkeleton() {
  return (
    <div className="space-y-4">
      <div className="flex gap-4">
        <Skeleton className="h-10 w-64" />
        <Skeleton className="h-10 w-40" />
      </div>
      <Card>
        <CardContent className="pt-6">
          <div className="space-y-4">
            {[1, 2, 3, 4, 5].map((i) => (
              <div key={i} className="flex items-center space-x-4">
                <Skeleton className="h-10 w-10 rounded-full" />
                <div className="space-y-2 flex-1">
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-3 w-24" />
                </div>
                <Skeleton className="h-6 w-16" />
                <Skeleton className="h-4 w-32" />
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function AdminUsersPage() {
  const navigate = useNavigate();
  const { user: currentUser } = useAuth();
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');
  const [togglingUserId, setTogglingUserId] = useState<string | null>(null);

  // Check admin access
  useEffect(() => {
    if (currentUser && !currentUser.isAdmin) {
      navigate({ to: '/dashboard', replace: true });
    }
  }, [currentUser, navigate]);

  // Fetch users
  useEffect(() => {
    const fetchUsers = async () => {
      try {
        setIsLoading(true);
        setError(null);
        const fetchedUsers = await adminApi.getUsers();
        setUsers(fetchedUsers);
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Failed to fetch users';
        setError(errorMessage);
      } finally {
        setIsLoading(false);
      }
    };

    if (currentUser?.isAdmin) {
      fetchUsers();
    }
  }, [currentUser]);

  // Filter users
  const filteredUsers = useMemo(() => {
    return users.filter((user) => {
      const matchesSearch = user.username.toLowerCase().includes(searchQuery.toLowerCase());

      switch (statusFilter) {
        case 'active':
          return matchesSearch && user.isActive;
        case 'inactive':
          return matchesSearch && !user.isActive;
        case 'admin':
          return matchesSearch && user.isAdmin;
        default:
          return matchesSearch;
      }
    });
  }, [users, searchQuery, statusFilter]);

  // Toggle user status
  const handleToggleUserStatus = async (user: AdminUser) => {
    // Prevent self-deactivation
    if (user.id === currentUser?.id) {
      toast.error('You cannot deactivate your own account');
      return;
    }

    try {
      setTogglingUserId(user.id);
      const updatedUser = await adminApi.updateUser(user.id, { is_active: !user.isActive });
      setUsers((prev) => prev.map((u) => (u.id === user.id ? updatedUser : u)));
      toast.success(`User ${updatedUser.isActive ? 'activated' : 'deactivated'} successfully`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to toggle user status';
      toast.error(errorMessage);
    } finally {
      setTogglingUserId(null);
    }
  };

  const clearFilters = () => {
    setSearchQuery('');
    setStatusFilter('all');
  };

  // Show loading state
  if (!currentUser?.isAdmin) {
    return null;
  }

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <Skeleton className="h-8 w-48 mb-2" />
            <Skeleton className="h-4 w-96" />
          </div>
          <Skeleton className="h-10 w-32" />
        </div>
        <UsersTableSkeleton />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Users className="h-6 w-6" />
            User Management
          </h1>
          <p className="text-muted-foreground">
            Manage all users in the system. Create, edit, activate, and deactivate user accounts.
          </p>
        </div>
        <Button asChild>
          <Link to="/admin/users/new">
            <UserPlus className="mr-2 h-4 w-4" />
            Create User
          </Link>
        </Button>
      </div>

      {/* Error Alert */}
      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription className="flex items-center justify-between">
            <span>{error}</span>
            <Button variant="outline" size="sm" onClick={() => setError(null)}>
              Dismiss
            </Button>
          </AlertDescription>
        </Alert>
      )}

      {/* Search and Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search by username..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9"
              />
            </div>
            <Select value={statusFilter} onValueChange={(v) => setStatusFilter(v as StatusFilter)}>
              <SelectTrigger className="w-full sm:w-48">
                <SelectValue placeholder="Filter by status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Users</SelectItem>
                <SelectItem value="active">Active Only</SelectItem>
                <SelectItem value="inactive">Inactive Only</SelectItem>
                <SelectItem value="admin">Admins Only</SelectItem>
              </SelectContent>
            </Select>
            <div className="flex items-center text-sm text-muted-foreground">
              Showing {filteredUsers.length} of {users.length} users
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Users Table */}
      <Card>
        <CardHeader>
          <CardTitle>Users ({filteredUsers.length})</CardTitle>
          <CardDescription>A list of all users registered in the system</CardDescription>
        </CardHeader>
        <CardContent>
          {filteredUsers.length === 0 ? (
            <div className="text-center py-12">
              <p className="text-muted-foreground">
                {searchQuery || statusFilter !== 'all'
                  ? 'No users match your search criteria.'
                  : 'No users found.'}
              </p>
              {(searchQuery || statusFilter !== 'all') && (
                <Button variant="link" onClick={clearFilters} className="mt-2">
                  Clear filters
                </Button>
              )}
            </div>
          ) : (
            <>
              {/* Mobile Card View */}
              <div className="block sm:hidden space-y-4">
                {filteredUsers.map((user) => (
                  <div key={user.id} className="bg-muted/50 rounded-lg p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center">
                          <span className="text-sm font-medium">
                            {user.username.charAt(0).toUpperCase()}
                          </span>
                        </div>
                        <div>
                          <p className="font-medium">{user.username}</p>
                          <UserStatusBadges user={user} />
                        </div>
                      </div>
                      <Button variant="link" asChild>
                        <Link to="/admin/users/$id" params={{ id: user.id }}>
                          View
                        </Link>
                      </Button>
                    </div>
                    <p className="text-xs text-muted-foreground mt-3">
                      Created {formatDate(user.createdAt)}
                    </p>
                  </div>
                ))}
              </div>

              {/* Desktop Table View */}
              <div className="hidden sm:block">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>User</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Created</TableHead>
                      <TableHead>Last Updated</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredUsers.map((user) => (
                      <TableRow key={user.id}>
                        <TableCell>
                          <div className="flex items-center gap-3">
                            <div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center">
                              <span className="text-sm font-medium">
                                {user.username.charAt(0).toUpperCase()}
                              </span>
                            </div>
                            <div>
                              <p className="font-medium">{user.username}</p>
                              <p className="text-xs text-muted-foreground">
                                ID: {user.id.substring(0, 8)}...
                              </p>
                            </div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <UserStatusBadges user={user} />
                        </TableCell>
                        <TableCell className="text-sm text-muted-foreground">
                          {formatDate(user.createdAt)}
                        </TableCell>
                        <TableCell className="text-sm text-muted-foreground">
                          {formatDate(user.updatedAt)}
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="flex justify-end gap-2">
                            <Button variant="link" size="sm" asChild>
                              <Link to="/admin/users/$id" params={{ id: user.id }}>
                                View
                              </Link>
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleToggleUserStatus(user)}
                              disabled={togglingUserId === user.id || user.id === currentUser?.id}
                            >
                              {togglingUserId === user.id ? (
                                <Loader2 className="h-4 w-4 animate-spin" />
                              ) : user.isActive ? (
                                'Deactivate'
                              ) : (
                                'Activate'
                              )}
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// frontend/src/routes/admin/users/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { admin, auth } from '$lib/stores';
  import { goto } from '$app/navigation';
  import { RouteGuard } from '$lib/components';
  import type { AdminUser } from '$lib/stores/admin.svelte';

  let isLoading = true;
  let searchQuery = '';
  let statusFilter: 'all' | 'active' | 'inactive' | 'admin' = 'all';

  // Reactive statements to track admin store state
  $: users = $admin.users;
  $: error = $admin.error;
  $: isAdminLoading = $admin.isLoading;

  // Filtered users based on search and filter criteria
  $: filteredUsers = users.filter(user => {
    const matchesSearch = user.username.toLowerCase().includes(searchQuery.toLowerCase());
    
    switch (statusFilter) {
      case 'active':
        return matchesSearch && user.isActive;
      case 'inactive':
        return matchesSearch && !user.isActive;
      case 'admin':
        return matchesSearch && user.isAdmin;
      default:
        return matchesSearch;
    }
  });

  onMount(async () => {
    // Check if user is admin
    if (!auth.value.user?.isAdmin) {
      goto('/dashboard');
      return;
    }

    try {
      await admin.fetchUsers();
    } catch (err) {
      console.error('Failed to fetch users:', err);
    } finally {
      isLoading = false;
    }
  });

  function formatDate(dateString: string) {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  function getUserStatusBadge(user: AdminUser) {
    const badges = [];
    
    if (user.isAdmin) {
      badges.push({ text: 'Admin', class: 'bg-purple-100 text-purple-800' });
    }
    
    if (!user.isActive) {
      badges.push({ text: 'Inactive', class: 'bg-red-100 text-red-800' });
    } else if (!user.isAdmin) {
      badges.push({ text: 'User', class: 'bg-green-100 text-green-800' });
    }
    
    return badges;
  }

  async function handleToggleUserStatus(user: AdminUser) {
    try {
      await admin.updateUser(user.id, { isActive: !user.isActive });
    } catch (error) {
      console.error('Failed to toggle user status:', error);
    }
  }
</script>

<RouteGuard requireAdmin={true}>
  <div class="space-y-6">
    <!-- Header -->
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-3xl font-bold leading-tight text-gray-900">User Management</h1>
        <p class="mt-2 text-sm text-gray-700">
          Manage all users in the system. Create, edit, activate, and deactivate user accounts.
        </p>
      </div>
      <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
        <a
          href="/admin/users/new"
          class="inline-flex items-center justify-center rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600"
        >
          <span class="mr-2">+</span>
          Create User
        </a>
      </div>
    </div>

    {#if error}
      <div class="rounded-md bg-red-50 p-4">
        <div class="flex">
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800">Error loading users</h3>
            <div class="mt-2 text-sm text-red-700">
              <p>{error}</p>
            </div>
            <div class="mt-4">
              <button
                on:click={() => admin.clearError()}
                type="button"
                class="rounded-md bg-red-50 px-3 py-2 text-sm font-medium text-red-800 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2"
              >
                Dismiss
              </button>
            </div>
          </div>
        </div>
      </div>
    {/if}

    <!-- Search and Filters -->
    <div class="bg-white shadow rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <!-- Search -->
          <div>
            <label for="search" class="block text-sm font-medium leading-6 text-gray-900">Search Users</label>
            <div class="mt-2">
              <input
                type="text"
                name="search"
                id="search"
                bind:value={searchQuery}
                placeholder="Search by username..."
                class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
              />
            </div>
          </div>

          <!-- Status Filter -->
          <div>
            <label for="status-filter" class="block text-sm font-medium leading-6 text-gray-900">Filter by Status</label>
            <div class="mt-2">
              <select
                id="status-filter"
                name="status-filter"
                bind:value={statusFilter}
                class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
              >
                <option value="all">All Users</option>
                <option value="active">Active Only</option>
                <option value="inactive">Inactive Only</option>
                <option value="admin">Admins Only</option>
              </select>
            </div>
          </div>

          <!-- Results Count -->
          <div class="flex items-end">
            <div class="text-sm text-gray-500">
              Showing {filteredUsers.length} of {users.length} users
            </div>
          </div>
        </div>
      </div>
    </div>

    {#if isLoading || isAdminLoading}
      <div class="flex justify-center py-12">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600" role="status" aria-label="Loading"></div>
      </div>
    {:else}
      <!-- Users Table -->
      <div class="bg-white shadow rounded-lg overflow-hidden">
        <div class="px-4 py-5 sm:p-6">
          <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">
            Users ({filteredUsers.length})
          </h3>
          
          {#if filteredUsers.length === 0}
            <div class="text-center py-12">
              <div class="text-gray-500">
                {#if searchQuery || statusFilter !== 'all'}
                  No users match your search criteria.
                {:else}
                  No users found.
                {/if}
              </div>
              {#if searchQuery || statusFilter !== 'all'}
                <button
                  on:click={() => { searchQuery = ''; statusFilter = 'all'; }}
                  class="mt-4 text-primary-600 hover:text-primary-500 text-sm font-medium"
                >
                  Clear filters
                </button>
              {/if}
            </div>
          {:else}
            <!-- Mobile Card View -->
            <div class="block sm:hidden space-y-4">
              {#each filteredUsers as user}
                <div class="bg-gray-50 rounded-lg p-4">
                  <div class="flex items-center justify-between">
                    <div class="flex items-center space-x-3">
                      <div class="h-10 w-10 rounded-full bg-gray-200 flex items-center justify-center">
                        <span class="text-sm font-medium text-gray-700">
                          {user.username.charAt(0).toUpperCase()}
                        </span>
                      </div>
                      <div>
                        <p class="text-sm font-medium text-gray-900">{user.username}</p>
                        <div class="flex flex-wrap gap-1 mt-1">
                          {#each getUserStatusBadge(user) as badge}
                            <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium {badge.class}">
                              {badge.text}
                            </span>
                          {/each}
                        </div>
                      </div>
                    </div>
                    <div class="flex space-x-2">
                      <a
                        href="/admin/users/{user.id}"
                        class="text-primary-600 hover:text-primary-900 text-sm font-medium"
                      >
                        View
                      </a>
                    </div>
                  </div>
                  <div class="mt-3 text-xs text-gray-500">
                    Created {formatDate(user.createdAt)}
                  </div>
                </div>
              {/each}
            </div>

            <!-- Desktop Table View -->
            <div class="hidden sm:block">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      User
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Created
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Last Updated
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Actions</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  {#each filteredUsers as user}
                    <tr class="hover:bg-gray-50">
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                          <div class="h-10 w-10 rounded-full bg-gray-200 flex items-center justify-center">
                            <span class="text-sm font-medium text-gray-700">
                              {user.username.charAt(0).toUpperCase()}
                            </span>
                          </div>
                          <div class="ml-4">
                            <div class="text-sm font-medium text-gray-900">{user.username}</div>
                            <div class="text-sm text-gray-500">ID: {user.id.substring(0, 8)}...</div>
                          </div>
                        </div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="flex flex-wrap gap-1">
                          {#each getUserStatusBadge(user) as badge}
                            <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium {badge.class}">
                              {badge.text}
                            </span>
                          {/each}
                        </div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {formatDate(user.createdAt)}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {formatDate(user.updatedAt)}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <div class="flex justify-end space-x-2">
                          <a
                            href="/admin/users/{user.id}"
                            class="text-primary-600 hover:text-primary-900"
                          >
                            View
                          </a>
                          <button
                            on:click={() => handleToggleUserStatus(user)}
                            class="text-gray-600 hover:text-gray-900"
                            title={user.isActive ? 'Deactivate user' : 'Activate user'}
                          >
                            {user.isActive ? 'Deactivate' : 'Activate'}
                          </button>
                        </div>
                      </td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          {/if}
        </div>
      </div>
    {/if}
  </div>
</RouteGuard>
