// ui/frontend/src/components/jobs/job-card.tsx
import { Link } from '@tanstack/react-router';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import {
  AlertTriangle,
  Clock,
  ExternalLink,
  FileText,
  Loader2,
  Trash2,
  XCircle,
} from 'lucide-react';
import type { Job } from '@/types';
import {
  JobStatus,
  getJobTypeLabel,
  getJobSourceLabel,
  getJobStatusLabel,
  getJobStatusVariant,
  formatDuration,
  formatRelativeTime,
  canCancelJob,
  canDeleteJob,
  isJobInProgress,
} from '@/types';

interface JobCardProps {
  job: Job;
  compact?: boolean;
  onView?: (job: Job) => void;
  onCancel?: (job: Job) => void;
  onDelete?: (job: Job) => void;
  isCancelling?: boolean;
  isDeleting?: boolean;
}

export function JobCard({
  job,
  compact = false,
  onView,
  onCancel,
  onDelete,
  isCancelling,
  isDeleting,
}: JobCardProps) {
  const showProgress = job.status === JobStatus.PROCESSING;

  if (compact) {
    return (
      <Link to="/jobs/$id" params={{ id: String(job.id) }} className="block">
        <Card className="transition-colors hover:border-primary/50">
          <CardContent className="flex items-center justify-between p-4">
            <div className="flex min-w-0 items-center gap-4">
              <Badge variant={getJobStatusVariant(job.status)}>
                {getJobStatusLabel(job.status)}
              </Badge>
              <div className="min-w-0">
                <div className="truncate text-sm font-medium">
                  {getJobTypeLabel(job.jobType)} - {getJobSourceLabel(job.source)}
                </div>
                <div className="text-xs text-muted-foreground">
                  {formatRelativeTime(job.createdAt)}
                </div>
              </div>
            </div>
            {showProgress && (
              <div className="w-24 flex-shrink-0">
                <Progress value={job.progress.percent} className="h-2" />
              </div>
            )}
          </CardContent>
        </Card>
      </Link>
    );
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div>
            <CardTitle className="text-lg">
              {getJobTypeLabel(job.jobType)} - {getJobSourceLabel(job.source)}
            </CardTitle>
            <p className="mt-1 text-sm text-muted-foreground">
              Started {formatRelativeTime(job.startedAt || job.createdAt)}
            </p>
          </div>
          <Badge variant={getJobStatusVariant(job.status)}>
            {isJobInProgress(job) && <Loader2 className="mr-1 h-3 w-3 animate-spin" />}
            {getJobStatusLabel(job.status)}
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Progress */}
        {showProgress && job.progress && (
          <div>
            <div className="mb-2 flex justify-between text-sm text-muted-foreground">
              <span>Progress</span>
              <span>
                {job.progress.completed +
                  job.progress.pendingReview +
                  job.progress.skipped +
                  job.progress.failed}{' '}
                / {job.progress.total} ({job.progress.percent}%)
              </span>
            </div>
            <Progress value={job.progress.percent} />
          </div>
        )}

        {/* Stats */}
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div className="flex items-center gap-2">
            <Clock className="h-4 w-4 text-muted-foreground" />
            <span className="text-muted-foreground">Duration:</span>
            <span className="font-medium">{formatDuration(job.durationSeconds)}</span>
          </div>
          {job.progress && job.progress.pendingReview > 0 && (
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-muted-foreground" />
              <span className="text-muted-foreground">Pending Review:</span>
              <span className="font-medium">{job.progress.pendingReview}</span>
            </div>
          )}
        </div>

        {/* Error message */}
        {job.errorMessage && (
          <div className="flex items-start gap-2 rounded-md bg-destructive/10 p-3 text-sm text-destructive">
            <AlertTriangle className="mt-0.5 h-4 w-4 flex-shrink-0" />
            <span>{job.errorMessage}</span>
          </div>
        )}
      </CardContent>

      <CardFooter className="gap-2 border-t pt-4">
        <Button
          variant="outline"
          size="sm"
          asChild
          className="ml-auto"
          onClick={() => onView?.(job)}
        >
          <Link to="/jobs/$id" params={{ id: String(job.id) }}>
            <ExternalLink className="mr-2 h-4 w-4" />
            View Details
          </Link>
        </Button>
        {canCancelJob(job) && onCancel && (
          <Button
            variant="outline"
            size="sm"
            onClick={() => onCancel(job)}
            disabled={isCancelling}
            className="text-amber-600 hover:bg-amber-50 hover:text-amber-700 dark:text-amber-400 dark:hover:bg-amber-950 dark:hover:text-amber-300"
          >
            {isCancelling ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <XCircle className="mr-2 h-4 w-4" />
            )}
            Cancel
          </Button>
        )}
        {canDeleteJob(job) && onDelete && (
          <Button
            variant="outline"
            size="sm"
            onClick={() => onDelete(job)}
            disabled={isDeleting}
            className="text-destructive hover:bg-destructive/10"
          >
            {isDeleting ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Trash2 className="mr-2 h-4 w-4" />
            )}
            Delete
          </Button>
        )}
      </CardFooter>
    </Card>
  );
}

// frontend/src/lib/components/JobCard.svelte
<script lang="ts">
	import type { Job } from '$lib/stores';
	import { JobStatus } from '$lib/stores';
	import {
		getJobTypeLabel,
		getJobSourceLabel,
		getJobStatusLabel,
		getJobStatusColor,
		formatDuration
	} from '$lib/types/jobs';
	import ProgressBar from './ProgressBar.svelte';

	interface Props {
		job: Job;
		compact?: boolean;
		onView?: (job: Job) => void;
		onCancel?: (job: Job) => void;
		onDelete?: (job: Job) => void;
	}

	let { job, compact = false, onView, onCancel, onDelete }: Props = $props();

	const isTerminal = $derived(job.is_terminal);
	const canCancel = $derived(
		!isTerminal && job.status !== JobStatus.PENDING && job.status !== JobStatus.AWAITING_REVIEW
	);
	const canDelete = $derived(isTerminal);
	const showProgress = $derived(
		job.status === JobStatus.PROCESSING || job.status === JobStatus.FINALIZING
	);

	function formatDate(dateStr: string | null): string {
		if (!dateStr) return '-';
		const date = new Date(dateStr);
		return date.toLocaleString();
	}

	function formatRelativeTime(dateStr: string | null): string {
		if (!dateStr) return '-';
		const date = new Date(dateStr);
		const now = new Date();
		const diffMs = now.getTime() - date.getTime();
		const diffMins = Math.floor(diffMs / 60000);
		const diffHours = Math.floor(diffMins / 60);
		const diffDays = Math.floor(diffHours / 24);

		if (diffMins < 1) return 'Just now';
		if (diffMins < 60) return `${diffMins}m ago`;
		if (diffHours < 24) return `${diffHours}h ago`;
		return `${diffDays}d ago`;
	}
</script>

{#if compact}
	<!-- Compact card for table rows -->
	<div
		class="flex items-center justify-between p-3 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600 transition-colors cursor-pointer"
		onclick={() => onView?.(job)}
		onkeydown={(e) => e.key === 'Enter' && onView?.(job)}
		role="button"
		tabindex="0"
	>
		<div class="flex items-center gap-4 min-w-0">
			<span
				class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {getJobStatusColor(
					job.status
				)}"
			>
				{getJobStatusLabel(job.status)}
			</span>
			<div class="min-w-0">
				<div class="text-sm font-medium text-gray-900 dark:text-white truncate">
					{getJobTypeLabel(job.job_type)} - {getJobSourceLabel(job.source)}
				</div>
				<div class="text-xs text-gray-500 dark:text-gray-400">
					{formatRelativeTime(job.created_at)}
				</div>
			</div>
		</div>
		{#if showProgress}
			<div class="w-24 flex-shrink-0">
				<ProgressBar value={job.progress_percent} size="sm" />
			</div>
		{/if}
	</div>
{:else}
	<!-- Full card -->
	<div
		class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden"
	>
		<div class="p-4">
			<!-- Header -->
			<div class="flex items-start justify-between">
				<div>
					<h3 class="text-lg font-medium text-gray-900 dark:text-white">
						{getJobTypeLabel(job.job_type)} - {getJobSourceLabel(job.source)}
					</h3>
					<p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
						Started {formatDate(job.started_at || job.created_at)}
					</p>
				</div>
				<span
					class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {getJobStatusColor(
						job.status
					)}"
				>
					{getJobStatusLabel(job.status)}
				</span>
			</div>

			<!-- Progress -->
			{#if showProgress}
				<div class="mt-4">
					<div class="flex justify-between text-sm text-gray-600 dark:text-gray-400 mb-1">
						<span>Progress</span>
						<span>{job.progress_current} / {job.progress_total}</span>
					</div>
					<ProgressBar value={job.progress_percent} />
				</div>
			{/if}

			<!-- Stats -->
			<div class="mt-4 grid grid-cols-2 gap-4 text-sm">
				<div>
					<span class="text-gray-500 dark:text-gray-400">Duration:</span>
					<span class="ml-1 text-gray-900 dark:text-white font-medium">
						{formatDuration(job.duration_seconds)}
					</span>
				</div>
				{#if job.review_item_count !== null && job.review_item_count > 0}
					<div>
						<span class="text-gray-500 dark:text-gray-400">Review items:</span>
						<span class="ml-1 text-gray-900 dark:text-white font-medium">
							{job.pending_review_count} / {job.review_item_count}
						</span>
					</div>
				{/if}
			</div>

			<!-- Error message -->
			{#if job.error_message}
				<div
					class="mt-4 p-3 bg-red-50 dark:bg-red-900/20 rounded-md text-sm text-red-700 dark:text-red-400"
				>
					{job.error_message}
				</div>
			{/if}
		</div>

		<!-- Actions -->
		<div
			class="px-4 py-3 bg-gray-50 dark:bg-gray-800/50 border-t border-gray-200 dark:border-gray-700 flex justify-end gap-2"
		>
			<button
				class="px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors"
				onclick={() => onView?.(job)}
			>
				View Details
			</button>
			{#if canCancel}
				<button
					class="px-3 py-1.5 text-sm font-medium text-yellow-700 dark:text-yellow-400 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-md hover:bg-yellow-100 dark:hover:bg-yellow-900/40 transition-colors"
					onclick={() => onCancel?.(job)}
				>
					Cancel
				</button>
			{/if}
			{#if canDelete}
				<button
					class="px-3 py-1.5 text-sm font-medium text-red-700 dark:text-red-400 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md hover:bg-red-100 dark:hover:bg-red-900/40 transition-colors"
					onclick={() => onDelete?.(job)}
				>
					Delete
				</button>
			{/if}
		</div>
	</div>
{/if}
