// ui/frontend/src/routes/_authenticated/dashboard.tsx
import { createFileRoute } from '@tanstack/react-router';
import { Link } from '@tanstack/react-router';
import { useCollectionStats } from '@/hooks';
import { ProgressStatistics, CurrentlyPlayingSection } from '@/components/dashboard';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Button } from '@/components/ui/button';
import { PlayStatus } from '@/types';

export const Route = createFileRoute('/_authenticated/dashboard')({
  head: () => ({ meta: [{ title: 'Dashboard | Nexorious' }] }),
  component: DashboardPage,
});

function DashboardSkeleton() {
  return (
    <div className="space-y-6">
      {/* Overview Stats Skeleton */}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <Card key={i}>
            <CardContent className="p-4">
              <Skeleton className="mb-2 h-4 w-24" />
              <Skeleton className="h-8 w-16" />
            </CardContent>
          </Card>
        ))}
      </div>
      {/* Progress Breakdown Skeleton */}
      <Card>
        <CardHeader>
          <Skeleton className="h-6 w-40" />
        </CardHeader>
        <CardContent className="space-y-4">
          {Array.from({ length: 8 }).map((_, i) => (
            <div key={i} className="space-y-2">
              <div className="flex justify-between">
                <Skeleton className="h-4 w-32" />
                <Skeleton className="h-4 w-12" />
              </div>
              <Skeleton className="h-2 w-full" />
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}

function EmptyState() {
  return (
    <Card>
      <CardContent className="flex flex-col items-center justify-center py-12">
        <div className="mb-4 text-6xl">🎮</div>
        <h3 className="mb-2 text-lg font-semibold">No games in your collection</h3>
        <p className="mb-4 text-center text-muted-foreground">
          Add some games to see your statistics and track your gaming progress!
        </p>
        <Button asChild>
          <Link to="/games/add">Add Your First Game</Link>
        </Button>
      </CardContent>
    </Card>
  );
}

function TopGenres({ genreStats }: { genreStats: Record<string, number> }) {
  const sortedGenres = Object.entries(genreStats)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5);

  if (sortedGenres.length === 0) {
    return null;
  }

  const maxCount = sortedGenres[0]?.[1] || 1;

  return (
    <Card>
      <CardHeader>
        <CardTitle>Top Genres</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        {sortedGenres.map(([genre, count]) => (
          <div key={genre} className="flex items-center justify-between">
            <span className="text-sm font-medium">{genre}</span>
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">{count}</span>
              <div className="h-2 w-20 overflow-hidden rounded-full bg-secondary">
                <div
                  className="h-full bg-indigo-500 transition-all"
                  style={{ width: `${(count / maxCount) * 100}%` }}
                />
              </div>
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

function PersonalStats({
  stats,
}: {
  stats: {
    averageRating: number | null;
    totalGames: number;
    totalHoursPlayed: number;
    pileOfShame: number;
    completionRate: number;
    completionStats: Record<PlayStatus, number>;
  };
}) {
  // Find the most played game stats
  const completedGames =
    (stats.completionStats[PlayStatus.COMPLETED] || 0) +
    (stats.completionStats[PlayStatus.MASTERED] || 0) +
    (stats.completionStats[PlayStatus.DOMINATED] || 0);

  return (
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle>Personal Stats</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Average Rating</span>
            <span className="text-sm text-muted-foreground">
              {stats.averageRating != null && stats.averageRating > 0
                ? `${stats.averageRating.toFixed(1)}/5`
                : 'N/A'}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Average Hours per Game</span>
            <span className="text-sm text-muted-foreground">
              {stats.totalGames > 0 ? (stats.totalHoursPlayed / stats.totalGames).toFixed(1) : 0}h
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Games Finished</span>
            <span className="text-sm text-muted-foreground">{completedGames}</span>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Game Insights</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Pile of Shame</span>
            <span className="text-sm text-muted-foreground">{stats.pileOfShame} games</span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Completion Rate</span>
            <span className="text-sm text-muted-foreground">
              {stats.completionRate.toFixed(1)}%
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">In Progress</span>
            <span className="text-sm text-muted-foreground">
              {stats.completionStats[PlayStatus.IN_PROGRESS] || 0} games
            </span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function DashboardPage() {
  const { data: stats, isLoading, error } = useCollectionStats();

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold">Dashboard</h1>
        <p className="text-muted-foreground">Your gaming statistics and insights</p>
      </div>

      {isLoading && <DashboardSkeleton />}

      {error && (
        <Card>
          <CardContent className="py-8 text-center text-destructive">
            Failed to load statistics. Please try again later.
          </CardContent>
        </Card>
      )}

      {stats && stats.totalGames === 0 && <EmptyState />}

      {stats && stats.totalGames > 0 && (
        <>
          <CurrentlyPlayingSection />

          <ProgressStatistics stats={stats} className="mb-6" />
          <TopGenres genreStats={stats.genreStats} />
          <div className="mt-6">
            <PersonalStats stats={stats} />
          </div>
        </>
      )}
    </div>
  );
}

// frontend/src/routes/dashboard/+page.svelte
<script lang="ts">
 import { userGames } from '$lib/stores';
 import { onMount } from 'svelte';
 import { goto } from '$app/navigation';
 import { RouteGuard, ProgressStatistics } from '$lib/components';
 
 onMount(() => {
  // Load user games for statistics - authentication is handled by RouteGuard
  userGames.fetchUserGames();
 });

 // Calculate statistics
 const userGamesList = $derived(userGames.value.userGames);
 const totalGames = $derived(userGamesList.length);
 const completedGames = $derived(userGamesList.filter(g => g.play_status === 'completed').length);
 const masteredGames = $derived(userGamesList.filter(g => g.play_status === 'mastered').length);
 const dominatedGames = $derived(userGamesList.filter(g => g.play_status === 'dominated').length);
 const inProgressGames = $derived(userGamesList.filter(g => g.play_status === 'in_progress').length);
 const notStartedGames = $derived(userGamesList.filter(g => g.play_status === 'not_started').length);
 const droppedGames = $derived(userGamesList.filter(g => g.play_status === 'dropped').length);
 const shelvedGames = $derived(userGamesList.filter(g => g.play_status === 'shelved').length);
 const totalHours = $derived(userGamesList.reduce((sum, userGame) => sum + (userGame.hours_played || 0), 0));
 const averageRating = $derived(userGamesList.filter(g => g.personal_rating).reduce((sum, userGame) => sum + (userGame.personal_rating || 0), 0) / userGamesList.filter(g => g.personal_rating).length || 0);
 const lovedGames = $derived(userGamesList.filter(g => g.is_loved).length);
 
 // Pile of Shame (owned games not started)
 const pileOfShame = $derived(notStartedGames);
 
 // Completion rate
 const completionRate = $derived(totalGames > 0 ? ((completedGames + masteredGames + dominatedGames) / totalGames) * 100 : 0);

 // Genre breakdown
 const genreStats = $derived(userGamesList.reduce((stats: Record<string, number>, userGame) => {
  const genre = userGame.game.genre || 'Unknown';
  stats[genre] = (stats[genre] || 0) + 1;
  return stats;
 }, {}));

 // Top genres
 const topGenres = $derived(Object.entries(genreStats)
  .sort(([,a], [,b]) => (b as number) - (a as number))
  .slice(0, 5));

 // Platform breakdown (would need platform data)
 // For now, we'll mock this - accessing totalGames to avoid unused variable warning
 $effect(() => {
  // Placeholder for future platform stats implementation
  totalGames; 
 });


</script>

<svelte:head>
 <title>Dashboard - Nexorious</title>
</svelte:head>

<RouteGuard requireAuth={true}>
<div>
 <!-- Header -->
 <div>
  <h1>Dashboard</h1>
  <p>
   Your gaming statistics and insights
  </p>
 </div>

 {#if userGames.value.isLoading}
  <div>
   <div>Loading statistics...</div>
  </div>
 {:else if totalGames === 0}
  <div>
   <div>
    No games in your collection yet. Add some games to see your statistics!
   </div>
   <button
    onclick={() => goto('/games/add')}
   >
    Add Your First Game
   </button>
  </div>
 {:else}
  <!-- Progress Statistics -->
  <ProgressStatistics userGames={userGamesList} class="mb-8" />
  
  <!-- Overview Statistics -->
  <div>
   <!-- Total Games -->
   <div>
    <div>
     <div>
      <div>
      </div>
     </div>
     <div>
      <dl>
       <dt>
        Total Games
       </dt>
       <dd>
        {totalGames}
       </dd>
      </dl>
     </div>
    </div>
   </div>

   <!-- Total Hours -->
   <div>
    <div>
     <div>
      <div>
      </div>
     </div>
     <div>
      <dl>
       <dt>
        Total Hours
       </dt>
       <dd>
        {totalHours.toLocaleString()}h
       </dd>
      </dl>
     </div>
    </div>
   </div>

   <!-- Completion Rate -->
   <div>
    <div>
     <div>
      <div>
      </div>
     </div>
     <div>
      <dl>
       <dt>
        Completion Rate
       </dt>
       <dd>
        {completionRate.toFixed(1)}%
       </dd>
      </dl>
     </div>
    </div>
   </div>

   <!-- Pile of Shame -->
   <div>
    <div>
     <div>
      <div>
      </div>
     </div>
     <div>
      <dl>
       <dt>
        Pile of Shame
       </dt>
       <dd>
        {pileOfShame}
       </dd>
      </dl>
     </div>
    </div>
   </div>
  </div>

  <!-- Detailed Statistics -->
  <div>
   <!-- Play Status Breakdown -->
   <div>
    <h3>
     Play Status Breakdown
    </h3>
    <div>
     <div>
      <span>Not Started</span>
      <div>
       <span>{notStartedGames}</span>
       <div>
        <div style="width: {totalGames > 0 ? (notStartedGames / totalGames) * 100 : 0}%"></div>
       </div>
      </div>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">In Progress</span>
      <div class="flex items-center space-x-2">
       <span class="text-sm text-gray-600">{inProgressGames}</span>
       <div class="w-20 bg-gray-200 rounded-full h-2">
        <div class="bg-blue-400 h-2 rounded-full" style="width: {totalGames > 0 ? (inProgressGames / totalGames) * 100 : 0}%"></div>
       </div>
      </div>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Completed</span>
      <div class="flex items-center space-x-2">
       <span class="text-sm text-gray-600">{completedGames}</span>
       <div class="w-20 bg-gray-200 rounded-full h-2">
        <div class="bg-green-400 h-2 rounded-full" style="width: {totalGames > 0 ? (completedGames / totalGames) * 100 : 0}%"></div>
       </div>
      </div>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Mastered</span>
      <div class="flex items-center space-x-2">
       <span class="text-sm text-gray-600">{masteredGames}</span>
       <div class="w-20 bg-gray-200 rounded-full h-2">
        <div class="bg-purple-400 h-2 rounded-full" style="width: {totalGames > 0 ? (masteredGames / totalGames) * 100 : 0}%"></div>
       </div>
      </div>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Dominated</span>
      <div class="flex items-center space-x-2">
       <span class="text-sm text-gray-600">{dominatedGames}</span>
       <div class="w-20 bg-gray-200 rounded-full h-2">
        <div class="bg-yellow-400 h-2 rounded-full" style="width: {totalGames > 0 ? (dominatedGames / totalGames) * 100 : 0}%"></div>
       </div>
      </div>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Shelved</span>
      <div class="flex items-center space-x-2">
       <span class="text-sm text-gray-600">{shelvedGames}</span>
       <div class="w-20 bg-gray-200 rounded-full h-2">
        <div class="bg-orange-400 h-2 rounded-full" style="width: {totalGames > 0 ? (shelvedGames / totalGames) * 100 : 0}%"></div>
       </div>
      </div>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Dropped</span>
      <div class="flex items-center space-x-2">
       <span class="text-sm text-gray-600">{droppedGames}</span>
       <div class="w-20 bg-gray-200 rounded-full h-2">
        <div class="bg-red-400 h-2 rounded-full" style="width: {totalGames > 0 ? (droppedGames / totalGames) * 100 : 0}%"></div>
       </div>
      </div>
     </div>
    </div>
   </div>

   <!-- Top Genres -->
   <div class="bg-white rounded-lg shadow p-6">
    <h3 class="text-lg font-semibold text-gray-900 mb-4">
     Top Genres
    </h3>
    <div class="space-y-3">
     {#each topGenres as [genre, count]}
      <div class="flex items-center justify-between">
       <span class="text-sm font-medium text-gray-700">{genre}</span>
       <div class="flex items-center space-x-2">
        <span class="text-sm text-gray-600">{count}</span>
        <div class="w-20 bg-gray-200 rounded-full h-2">
         <div class="bg-indigo-400 h-2 rounded-full" style="width: {(count / totalGames) * 100}%"></div>
        </div>
       </div>
      </div>
     {/each}
    </div>
   </div>
  </div>

  <!-- Additional Statistics -->
  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
   <!-- Personal Stats -->
   <div class="bg-white rounded-lg shadow p-6">
    <h3 class="text-lg font-semibold text-gray-900 mb-4">
     Personal Stats
    </h3>
    <div class="space-y-3">
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Average Rating</span>
      <span class="text-sm text-gray-600">
       {averageRating > 0 ? `${averageRating.toFixed(1)}/5` : 'N/A'}
      </span>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Loved Games</span>
      <span class="text-sm text-gray-600">{lovedGames}</span>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Average Hours per Game</span>
      <span class="text-sm text-gray-600">
       {totalGames > 0 ? (totalHours / totalGames).toFixed(1) : 0}h
      </span>
     </div>
    </div>
   </div>

   <!-- Game Insights -->
   <div class="bg-white rounded-lg shadow p-6">
    <h3 class="text-lg font-semibold text-gray-900 mb-4">
     Game Insights
    </h3>
    <div class="space-y-3">
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Pile of Shame</span>
      <span class="text-sm text-gray-600">{pileOfShame} games</span>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Completion Rate</span>
      <span class="text-sm text-gray-600">{completionRate.toFixed(1)}%</span>
     </div>
     <div class="flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">Most Played Game</span>
      <span class="text-sm text-gray-600">
       {#if userGamesList.length > 0}
        {userGamesList.reduce((max, game) => game.hours_played > max.hours_played ? game : max).game.title}
       {:else}
        None
       {/if}
      </span>
     </div>
    </div>
   </div>
  </div>
 {/if}
</div>
</RouteGuard>
