// ui/frontend/src/routes/_authenticated/admin/users/new.tsx
import { useState, useEffect, useMemo } from 'react';
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useAuth } from '@/providers';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';
import { ArrowLeft, AlertCircle, Loader2, Eye, EyeOff, UserPlus } from 'lucide-react';
import * as adminApi from '@/api/admin';

export const Route = createFileRoute('/_authenticated/admin/users/new')({
  head: () => ({ meta: [{ title: 'New User | Nexorious' }] }),
  component: CreateUserPage,
});

interface PasswordStrength {
  score: number;
  label: string;
}

function calculatePasswordStrength(password: string): PasswordStrength {
  let score = 0;

  if (password.length >= 6) score += 1;
  if (password.length >= 8) score += 1;
  if (password.length >= 12) score += 1;
  if (/[A-Z]/.test(password)) score += 1;
  if (/[a-z]/.test(password)) score += 1;
  if (/[0-9]/.test(password)) score += 1;
  if (/[^A-Za-z0-9]/.test(password)) score += 1;

  if (score <= 2) return { score, label: 'Weak' };
  if (score <= 4) return { score, label: 'Medium' };
  return { score, label: 'Strong' };
}

function CreateUserPage() {
  const navigate = useNavigate();
  const { user: currentUser } = useAuth();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isAdmin, setIsAdmin] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  // Derived values
  const passwordStrength = useMemo(() => calculatePasswordStrength(password), [password]);
  const passwordsMatch = password && confirmPassword && password === confirmPassword;

  // Check admin access
  useEffect(() => {
    if (currentUser && !currentUser.isAdmin) {
      navigate({ to: '/dashboard', replace: true });
    }
  }, [currentUser, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    // Validation
    if (!username.trim()) {
      setError('Username is required');
      return;
    }

    if (username.trim().length < 3) {
      setError('Username must be at least 3 characters');
      return;
    }

    if (!password) {
      setError('Password is required');
      return;
    }

    if (password !== confirmPassword) {
      setError('Passwords do not match');
      return;
    }

    if (password.length < 6) {
      setError('Password must be at least 6 characters long');
      return;
    }

    setIsLoading(true);

    try {
      await adminApi.createUser({
        username: username.trim(),
        password,
        is_admin: isAdmin,
      });
      toast.success('User created successfully');
      navigate({ to: '/admin/users' });
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to create user';
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  // Show loading state
  if (!currentUser?.isAdmin) {
    return null;
  }

  const canSubmit =
    username.trim().length >= 3 && password.length >= 6 && passwordsMatch && !isLoading;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link to="/admin/users" aria-label="Back to users">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-1">
            <Link to="/admin/users" className="hover:text-foreground">
              User Management
            </Link>
            <span>/</span>
            <span>Create User</span>
          </nav>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <UserPlus className="h-6 w-6" />
            Create New User
          </h1>
          <p className="text-muted-foreground">
            Create a new user account with username and password. You can also assign admin
            privileges.
          </p>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Main Form */}
        <div className="lg:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle>User Details</CardTitle>
              <CardDescription>Enter the new user&apos;s account information</CardDescription>
            </CardHeader>
            <CardContent>
              {error && (
                <Alert variant="destructive" className="mb-6">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              <form onSubmit={handleSubmit} className="space-y-6">
                {/* Username */}
                <div>
                  <Label htmlFor="username">
                    Username <span className="text-destructive">*</span>
                  </Label>
                  <Input
                    id="username"
                    type="text"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    placeholder="Enter username"
                    className="mt-1"
                    disabled={isLoading}
                    autoComplete="username"
                  />
                  <p className="mt-1 text-xs text-muted-foreground">
                    Username will be used for login and display purposes
                  </p>
                </div>

                {/* Password */}
                <div className="grid gap-4 sm:grid-cols-2">
                  <div>
                    <Label htmlFor="password">
                      Password <span className="text-destructive">*</span>
                    </Label>
                    <div className="relative mt-1">
                      <Input
                        id="password"
                        type={showPassword ? 'text' : 'password'}
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        placeholder="Enter password"
                        className="pr-10"
                        disabled={isLoading}
                        autoComplete="new-password"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="absolute inset-y-0 right-0 flex items-center pr-3"
                        aria-label={showPassword ? 'Hide password' : 'Show password'}
                      >
                        {showPassword ? (
                          <EyeOff className="h-4 w-4 text-muted-foreground" />
                        ) : (
                          <Eye className="h-4 w-4 text-muted-foreground" />
                        )}
                      </button>
                    </div>

                    {/* Password Strength Meter */}
                    {password && (
                      <div className="mt-2 space-y-1">
                        <div className="flex items-center gap-2">
                          <Progress
                            value={(passwordStrength.score / 7) * 100}
                            className="h-2 flex-1"
                          />
                          <span className="text-xs text-muted-foreground">
                            {passwordStrength.label}
                          </span>
                        </div>
                      </div>
                    )}
                  </div>

                  <div>
                    <Label htmlFor="confirmPassword">
                      Confirm Password <span className="text-destructive">*</span>
                    </Label>
                    <div className="relative mt-1">
                      <Input
                        id="confirmPassword"
                        type={showConfirmPassword ? 'text' : 'password'}
                        value={confirmPassword}
                        onChange={(e) => setConfirmPassword(e.target.value)}
                        placeholder="Confirm password"
                        className={`pr-10 ${
                          confirmPassword
                            ? passwordsMatch
                              ? 'border-green-500'
                              : 'border-destructive'
                            : ''
                        }`}
                        disabled={isLoading}
                        autoComplete="new-password"
                      />
                      <button
                        type="button"
                        onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                        className="absolute inset-y-0 right-0 flex items-center pr-3"
                        aria-label={showConfirmPassword ? 'Hide password' : 'Show password'}
                      >
                        {showConfirmPassword ? (
                          <EyeOff className="h-4 w-4 text-muted-foreground" />
                        ) : (
                          <Eye className="h-4 w-4 text-muted-foreground" />
                        )}
                      </button>
                    </div>
                    {confirmPassword && !passwordsMatch && (
                      <p className="mt-1 text-xs text-destructive">Passwords do not match</p>
                    )}
                  </div>
                </div>

                {/* Admin Role */}
                <div className="flex items-start space-x-3 p-4 bg-muted/50 rounded-lg">
                  <Checkbox
                    id="isAdmin"
                    checked={isAdmin}
                    onCheckedChange={(checked) => setIsAdmin(checked === true)}
                    disabled={isLoading}
                  />
                  <div>
                    <label htmlFor="isAdmin" className="font-medium text-sm cursor-pointer">
                      Admin User
                    </label>
                    <p className="text-xs text-muted-foreground">
                      Grant administrative privileges to this user. Admin users can manage other
                      users and system settings.
                    </p>
                  </div>
                </div>

                {/* Form Actions */}
                <div className="flex justify-end gap-3 pt-4 border-t">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => navigate({ to: '/admin/users' })}
                    disabled={isLoading}
                  >
                    Cancel
                  </Button>
                  <Button type="submit" disabled={!canSubmit}>
                    {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    Create User
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>

        {/* Requirements Info Box */}
        <div className="hidden lg:block">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">Requirements</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2">
                  Username
                </h4>
                <ul className="space-y-1 text-xs text-muted-foreground">
                  <li>3-100 characters long</li>
                  <li>Letters, numbers, underscore only</li>
                  <li>No spaces or special characters</li>
                  <li>Must be unique</li>
                </ul>
              </div>

              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2">
                  Password
                </h4>
                <ul className="space-y-1 text-xs text-muted-foreground">
                  <li>Minimum 6 characters</li>
                  <li>At least one uppercase letter (recommended)</li>
                  <li>At least one number (recommended)</li>
                  <li>Special character (recommended)</li>
                </ul>
              </div>

              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2">
                  Admin Privileges
                </h4>
                <ul className="space-y-1 text-xs text-muted-foreground">
                  <li>Access to user management</li>
                  <li>System settings configuration</li>
                  <li>Platform administration</li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/admin/users/new/+page.svelte
<script lang="ts">
  import { admin } from '$lib/stores';
  import { goto } from '$app/navigation';
  import { RouteGuard } from '$lib/components';

  let username = '';
  let password = '';
  let confirmPassword = '';
  let isAdmin = false;
  let isLoading = false;
  let error = '';

  async function handleCreateUser() {
    // Reset error
    error = '';

    // Validation
    if (!username.trim()) {
      error = 'Username is required';
      return;
    }

    if (!password) {
      error = 'Password is required';
      return;
    }

    if (password !== confirmPassword) {
      error = 'Passwords do not match';
      return;
    }

    if (password.length < 6) {
      error = 'Password must be at least 6 characters long';
      return;
    }

    isLoading = true;

    try {
      await admin.createUser(username.trim(), password, isAdmin);
      // Navigate back to users list on success
      goto('/admin/users');
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to create user';
    } finally {
      isLoading = false;
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      handleCreateUser();
    }
  }
</script>

<svelte:head>
  <title>Create User - Admin - Nexorious</title>
</svelte:head>

<RouteGuard requireAdmin={true}>
  <div class="space-y-6">
    <!-- Header -->
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <nav class="flex" aria-label="Breadcrumb">
          <ol class="flex items-center space-x-4">
            <li>
              <div>
                <a href="/admin/users" class="text-sm font-medium text-gray-500 hover:text-gray-700">
                  User Management
                </a>
              </div>
            </li>
            <li>
              <div class="flex items-center">
                <svg class="h-4 w-4 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                </svg>
                <span class="ml-4 text-sm font-medium text-gray-700">Create User</span>
              </div>
            </li>
          </ol>
        </nav>
        <h1 class="mt-2 text-3xl font-bold leading-tight text-gray-900">Create New User</h1>
        <p class="mt-2 text-sm text-gray-700">
          Create a new user account with username and password. You can also assign admin privileges.
        </p>
      </div>
    </div>

    <!-- Form -->
    <div class="bg-white shadow rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        {#if error}
          <div class="mb-6 rounded-md bg-red-50 p-4">
            <div class="flex">
              <div class="flex-shrink-0">
                <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
                </svg>
              </div>
              <div class="ml-3">
                <p class="text-sm text-red-800">
                  {error}
                </p>
              </div>
            </div>
          </div>
        {/if}

        <form onsubmit={(e) => { e.preventDefault(); handleCreateUser(); }} class="space-y-6">
          <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <!-- Username -->
            <div class="sm:col-span-2">
              <label for="username" class="form-label">
                Username <span class="text-red-500">*</span>
              </label>
              <input
                id="username"
                type="text"
                bind:value={username}
                onkeydown={handleKeydown}
                required
                placeholder="Enter username"
                class="form-input"
                disabled={isLoading}
                autocomplete="username"
              />
              <p class="mt-1 text-xs text-gray-500">
                Username will be used for login and display purposes
              </p>
            </div>

            <!-- Password -->
            <div>
              <label for="password" class="form-label">
                Password <span class="text-red-500">*</span>
              </label>
              <input
                id="password"
                type="password"
                bind:value={password}
                onkeydown={handleKeydown}
                required
                placeholder="Enter password"
                class="form-input"
                disabled={isLoading}
                autocomplete="new-password"
              />
              <p class="mt-1 text-xs text-gray-500">
                Minimum 6 characters required
              </p>
            </div>

            <!-- Confirm Password -->
            <div>
              <label for="confirm-password" class="form-label">
                Confirm Password <span class="text-red-500">*</span>
              </label>
              <input
                id="confirm-password"
                type="password"
                bind:value={confirmPassword}
                onkeydown={handleKeydown}
                required
                placeholder="Confirm password"
                class="form-input"
                disabled={isLoading}
                autocomplete="new-password"
              />
            </div>

            <!-- Admin Role -->
            <div class="sm:col-span-2">
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <input
                    id="is-admin"
                    type="checkbox"
                    bind:checked={isAdmin}
                    disabled={isLoading}
                    class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                  />
                </div>
                <div class="ml-3 text-sm">
                  <label for="is-admin" class="font-medium text-gray-700">Admin User</label>
                  <p class="text-gray-500">
                    Grant administrative privileges to this user. Admin users can manage other users and system settings.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <!-- Form Actions -->
          <div class="flex justify-end space-x-3 pt-6 border-t border-gray-200">
            <button
              type="button"
              onclick={() => goto('/admin/users')}
              disabled={isLoading}
              class="inline-flex justify-center py-2 px-4 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isLoading}
              class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {#if isLoading}
                <svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Creating User...
              {:else}
                Create User
              {/if}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</RouteGuard>
